### ISSUE TITLE
Download the source code but can't build

### ISSUE THREAD

**Issue by budiyantochen** [Microsoft/Recurring-Integrations-Scheduler#1]
Where can get the executable package?
Is it the source code only content classes without form?

**Comment by TomekMelissa** [comment]
To run the RIS App you need to set Scheduler as your startup project. Build process should restore all nuget packages needed.

**Comment by budiyantochen** [comment]
Hi,

Thank able to start the project.
However, where I can get the installer file  per the wiki installation step?

Will this work for on-premise? Since it required to be registered on Azure?


Sent from Mail for Windows 10

**Comment by TomekMelissa** [comment]
Installer is in [Releases section on Github](https://github.com/Microsoft/Recurring-Integrations-Scheduler/releases). If you want to compile your own follow short readme in [Setup folder](https://github.com/Microsoft/Recurring-Integrations-Scheduler/tree/master/Setup)
