### ISSUE TITLE
Job export D365 Forbidden

### ISSUE THREAD

**Issue by robigand** [Microsoft/Recurring-Integrations-Scheduler#10]
Hello 
I get this error when running export job:

RecurringIntegrationsScheduler.Job.Export - Si sono verificati uno o più errori.
System.AggregateException: Si sono verificati uno o più errori. ---> System.Exception: Job: Export jobs.export2. Download failure. Forbidden
   in RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   in System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   in RecurringIntegrationsScheduler.Job.Export.Execute(IJobExecutionContext context)
---> (Eccezione interna 0) System.Exception: Job: Export jobs.export2. Download failure. Forbidden
   in RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()<---

In validate instance setting I get OK message.
In d365 i have granted access for AAD application.

Version of RIS is 1.0.0.0
Can someone help me please?
Thanks 
Robetrto

**Comment by TomekMelissa** [comment]
Are you sure you are working with PU5 or above? Export and import methods will not work with earlier versions.

**Comment by robigand** [comment]
Hi
Thank you very much for the answer.
My D365 version is:
[cid:image001.png@01D3472C.F74DCAC0]

Roberto Gandolfi
Dynamics AX Technical Consultant
Cell. +39 366 7607811
roberto.gandolfi@pa-group.com<mailto:roberto.gandolfi@pa-group.com>

PA Expertise Srl
Sede: Direzionale Meridiana, Via E. Cristoni, 84  | 40033 Casalecchio di Reno (BO)
Filiale: Via Carlo Levi, 2/b  | 42124 Reggio Emilia
Filiale: Via Rosellini, 12 | 20124 Milano
Tel. +39 051 19936012 | Fax +39 051 19936013
www.pa-group.com<http://www.pa-group.com/>

[logo-firma-PA-Group]
Questo messaggio contiene informazioni confidenziali appartenenti a Gruppo Partners Associates ed è destinato unicamente ai destinatari. La divulgazione o copia, anche parziale e non autorizzata, è proibita. Gruppo Partners Associates non è responsabile se questo messaggio viene modificato o falsificato. Se non siete i designati riceventi di questo messaggio, cancellatelo immediatamente dal vostro sistema e avvisate il mittente dell’errore dell’indirizzo di consegna e della cancellazione del messaggio.

This e-mail contains confidential information belonging to Gruppo Partners Associates and it is intended solely for the address. The unauthorised disclosure or copying either whole or partial of this e-mail, is prohibited. Gruppo Partners Associates shall not be liable for this e-mail if modified or falsified. If  you are not the intended recipient of this e-mail, please delete it immediately from your system and notify the sender of the wrong delivery and the mail deletion.

Da: Tomek Melissa [mailto:notifications@github.com]
Inviato: venerdì 13 ottobre 2017 11:04
A: Microsoft/Recurring-Integrations-Scheduler <Recurring-Integrations-Scheduler@noreply.github.com>
Cc: Roberto Gandolfi | PA Group <roberto.gandolfi@pa-group.com>; Author <author@noreply.github.com>
Oggetto: Re: [Microsoft/Recurring-Integrations-Scheduler] Job export D365 Forbidden (#10)


Are you sure you are working with PU5 or above? Export and import methods will not work with earlier versions.
