### ISSUE TITLE
RecurringIntegrationsScheduler.Job.Import - Target legal entity is not valid: Input

### ISSUE THREAD

**Issue by BruceScott-Afflink** [microsoft/Recurring-Integrations-Scheduler#100]
I'm getting the following error while trying to setup RIS 3.0 import job.
I have my company entered in the Single target company field.

First error:
RecurringIntegrationsScheduler.Job.Import - Job: Import jobs.ImportJob1. Target legal entity is not valid: Input

2nd error
RecurringIntegrationsScheduler.Job.Import - Job: Import jobs.ImportJob1. Upload failed for file: C:\temp\Inbound\Orders\Input\MyEntity.xml. Failure response:  Status: BadRequest, Reason: Bad Request. ImportFromPackage failed request's parameters: 
packageUrl: https://d365xx.blob.core.windows.net/dmf/nnn
definitionGroupId: My_Imports
executionId: My_Imports-2020-02-19_17-36-15-4153711b-696b-46bb-8b45-38d0517350df
execute: True
overwrite: False
legalEntityId: Input

**Comment by TomekMelissa** [comment]
This bug is now fixed, but not released yet. Please use multicompany import option with subfolder for the time being.

**Comment by TomekMelissa** [comment]
This is fixed and release in v. 3.1.0
