### ISSUE TITLE
One or more errors occurred. Handler did not return a response message.

### ISSUE THREAD

**Issue by MZade** [microsoft/Recurring-Integrations-Scheduler#103]
### Expected behavior and actual behavior.
When trying to use the "Validate" functionality, the validation should generate no errors if the used credentials and references are valid.

### Steps to reproduce the problem.
When we try to use a given valid Client+Secret key combination against a given D365FO environment, we get the following error message.
This is while when we try the same ClientApp+Secret using fiddler we can easily call D365FO services.

![image](https://user-images.githubusercontent.com/19854220/76619780-f95f6880-652b-11ea-8bdc-cd68854a2268.png)

### Specifications like the version of RIS and platform and application version of D365FO.
![image](https://user-images.githubusercontent.com/19854220/76619928-53602e00-652c-11ea-84e1-c71a8ac9bd10.png)

**Comment by MZade** [comment]
Here you have more screenshots from the RIS event log at the moment when we click on "Validate".
We see only these two entries and no further entries are made when we click on "Validate"

![image](https://user-images.githubusercontent.com/19854220/76620031-93271580-652c-11ea-9e32-6035fae99997.png)

![image](https://user-images.githubusercontent.com/19854220/76620093-adf98a00-652c-11ea-82c8-eaacfe04044f.png)

**Comment by TomekMelissa** [comment]
finally someone tested it :) This one is fixed already. I will work on others today. thanks Mehrdad
