### ISSUE TITLE
QUESTION: Import job scheduling more frequently

### ISSUE THREAD

**Issue by MZade** [microsoft/Recurring-Integrations-Scheduler#104]
When modifying i.e. the **Standalone_schedule.xml** and changing the **repeat-interval** value for import jobs to a value less than 60000 ms it seems to work properly.
What would be the reason to not allow going beyond the 60000 ms and allow users to have more frequent import jobs planned?

**Comment by TomekMelissa** [comment]
It is common sense. why would you need to run any job more frequent than every minute? Without boundaries most users would run those jobs every second, just because they can. The overhead of processing such jobs probably would erase any gains from more frequent schedule.
