### ISSUE TITLE
Question about contacts

### ISSUE THREAD

**Issue by JarLob** [microsoft/Recurring-Integrations-Scheduler#107]
How could I privately report a security vulnerability?

**Comment by TomekMelissa** [comment]
send me an email tmelissa at microsoft.com

**Comment by JarLob** [comment]
Did it days ago. Please check your spam folder.

**Comment by TomekMelissa** [comment]
I could not find anything. Please send it again. Thank you.

**Comment by JarLob** [comment]
Ok, just did it. Let me know if it didn't pass through.
