### ISSUE TITLE
Authority validation failed

### ISSUE THREAD

**Issue by ashwinjugurnauth** [microsoft/Recurring-Integrations-Scheduler#109]
I am currently running version 2.4.0 and have tried to install latest version 3.1.2. I have put the same configuration and have set up an import job. However, when I click on validate, I get an error regarding authority validation. Please note that I am on version 10.0.9 on-premise.

Please help :(

**Comment by TomekMelissa** [comment]
You should start configuration from scratch. version 3 is not compatible with Schedule.xml file of previous versions.

**Comment by ashwinjugurnauth** [comment]
Oh sorry, I did not phrase that correctly, my bad. I actually started the configuration from scratch, both for the parameters, and the DMF jobs

**Comment by ashwinjugurnauth** [comment]
Hello, 

I think I have found the issue by running a fiddler, it seems that the current version attempts to connect to login.microsoft.com instead of taking the authentication endpoint provided in the parameters. 

![image](https://user-images.githubusercontent.com/50940114/81035562-8da2d780-8eac-11ea-8b8d-d38fa6e01c63.png)

![image](https://user-images.githubusercontent.com/50940114/81035580-9a273000-8eac-11ea-8096-ed850e087873.png)

Please help :(

**Comment by TomekMelissa** [comment]
Check 3.1.3

**Comment by ashwinjugurnauth** [comment]
Hello

Unfortunately it's not working, I'm still getting an issue :(. From what I see, in earlier versions the entry point is the application url, which then redirects to the adfs with an application id to get a token. Here it is directly accessing the adfs, and getting the error message The client is not allowed to access the requested resource.

![image](https://user-images.githubusercontent.com/50940114/81061539-949a0c00-8ee5-11ea-9923-63a5fc42d89b.png)

**Comment by TomekMelissa** [comment]
well. I am "fixing" it blind, because I do not have on-prem instance to test it with.
Could you save sessions for old (working) version and newest one in Fiddler and share those with me? Store it on onedrive and send me a link to tmelissa at microsoft.com

**Comment by ashwinjugurnauth** [comment]
Unfortunately I do not have a onedrive, I sent both of them to you by mail.
