### ISSUE TITLE
Cannot compile a fork of the solution on VS 2015

### ISSUE THREAD

**Issue by diegomancassola** [Microsoft/Recurring-Integrations-Scheduler#11]
I able to compile the solution using Visual Studio 2015 by add NUGET references on solutions to these two packages:

* Microsoft.Net.Compilers
* System.ValueTuple

Code is write with some new features of C#7
[https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015](https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015)

**Comment by TomekMelissa** [comment]
Thank you Diego. I will add this to wiki
