### ISSUE TITLE
Issue with import for on premise D365FO

### ISSUE THREAD

**Issue by kiran211** [microsoft/Recurring-Integrations-Scheduler#110]
I had done setup for export and import jobs. Export is working fine with out any issue in my on-premise system. when i try to import I'm facing below error and always file is moved to error folder. I don't have access to target system to validate event logs.  Any help would be highly appreciated.

Note: when i manually import through data management it is working fine and tried by checking "Overwrite data project definition" also

![image](https://user-images.githubusercontent.com/64577787/80681770-f4a44300-8ade-11ea-85ee-ee10bd3cb882.png)

RecurringIntegrationsScheduler.Job.Import - Job: Import jobs.custimport. Upload failed for file: C:\integration\Input\customerv3export-Customers V3imp.xlsx. Failure response:  Status: InternalServerError, Reason: Internal Server Error

**Comment by TomekMelissa** [comment]
Import job is using package API. So you need to upload packages not raw input files. You need to use package template or create package yourself.

**Comment by kiran211** [comment]
Got it able to import now after creating my own package
