### ISSUE TITLE
RIS Feature Request-Ability to add multiple CSV files for a data package template

### ISSUE THREAD

**Issue by ahrazusmani** [microsoft/Recurring-Integrations-Scheduler#111]
### When setting up a upload job for an on-premise deployment.  We are trying to get RIS to pick up multiple CSV files from the Input folder to process against a template with multiple entities\CSV files.  RIS seems to pick up the files in the input folder but is unable to map them to the correct entities.  If we map the file names in the input to the values the package expects, would it be expected that this would work correctly?
Repro steps: 
Create a template with multiple entities and add multiple corresponding files into Input and run the job.
###

**Comment by TomekMelissa** [comment]
No. Package template works only for cases where there is one entity - one input file in the package. If you want to upload packages with multiple entities/files in it, you need to create package yourself, earlier in the process and use RIS for upload of those ready packages from input folder.
