### ISSUE TITLE
Cronmaker doesnt work in Version 3.2.0

### ISSUE THREAD

**Issue by sjenner-sysadmin** [microsoft/Recurring-Integrations-Scheduler#112]
We updated the RIS Tool to version 3.2.0 and now, we cant use the Cron trigger for our Export and Import Jobs anymore. It´s greyed out. Simple Trigger doesnt work correct as well. We can´t change the starting time. If we change the time, the system doesn´t  recognize this correctly.  The tool is running on a Windows 2016 Datacenter.

**Comment by TomekMelissa** [comment]
Thank you for reporting this. Could you verify 3.2.1? As you are using cron triggers it will help me validate one more fix in this release regarding timezones in schedule.xml file

**Comment by sjenner-sysadmin** [comment]
Thank you, with the Update Cron is working again. 
How can I now use the saved Backup .xml after installing the new Version. Don´t want to create all the jobs all the time I update the tool. Can you also add the possibility to change the search pattern for the input file. When we change it, we can´t select the input file from the appropriate folder which has to done, otherweise we cant create the job.

**Comment by TomekMelissa** [comment]
You should just install new version over old one and your scheduler service should work with old schedule.xml version. I try to keep major versions backward compatible. 
Could you elaborate on the problem with search pattern? maybe with some screenshots?

**Comment by sjenner-sysadmin** [comment]
Sorry to say, but after I installed the new version, all scheduled jobs are gone. When I re-name my backup scheduler file to schedule.xml and copy it to the installation folder, the tool doesn´t regecognize this. There are still no jobs available and I need to add all jobs again

**Comment by TomekMelissa** [comment]
I want to make sure we are on the same page so I will try to explain the basics.
Please be aware that RIS has two components. RIS app is used for configuration and running so called standalone scheduler and RIS service is used for executing jobs. It is a windows service. RIS app can be used to connect to that service and add/edit jobs. The service needs to run obviously to make that possible. When you add a job to the RIS service it will be executed based on schedule until the service is shut down. Next time when service will be started it will look for Schedule.xml file in main RIS folder to read all jobs definitions. It is RIS app responsibility to catch any changes done to the schedule of running RIS service you do and prompt you to save the Schedule.xml file when you try to close RIS app.
I suspect that in your case you did not restart the service after you copied your backup Schedule.xml file.

**Comment by sjenner-sysadmin** [comment]
Hi, Thanks for that Explanation. This helps a lot and solved my problem with the backup XML. Restarting the service. And now I can confirm that Cron is working again and also the Simple Trigger fix with the starting time. Great. Thanks.

**Comment by TomekMelissa** [comment]
Great to see
