### ISSUE TITLE
Microsoft Graph is not being initialized when called from Quartz server

### ISSUE THREAD

**Issue by DShukvaniProdware** [microsoft/Recurring-Integrations-Scheduler#114]
### Expected behavior and actual behavior.

I expect to import Microsoft Graph assembly and use it when running `Job.Import` from Quartz.Server.

### Error
When I tap in the Microsoft.Graph library in two projects: `Scheduler` and `Job.Import`, in runtime object with type `GraphServiceClient` is not being created and throws error about Newtonsoft 6.0.0.0 not being loaded.

### Steps to reproduce the problem.

please review my [repository](https://github.com/DShukvaniProdware/Recurring-Integration-Service-With-OneDrive) created specially for this issue. You will find more specific details there.

### Specifications like the version of RIS and platform and application version of D365FO.

The RIS version is 3.2.2; as for D365 version, it's not important at the time being, connection with D365 works as expected

**Comment by TomekMelissa** [comment]
I think you need to rethink what you are trying to achieve. AFAIK onedrive API always requires user interactions. It means you cannot use it in daemon/service scenarios. Even in your example you are using interactive flow. IMO this is why it works in an interactive app, but does not in service. This is not, by any means RIS flaw...
Why do you need to work with OneDrive API anyway? Can't you just use its folders as any other local folder?

**Comment by DShukvaniProdware** [comment]
You can use Microsoft Graph to do various actions on OneDrive/SharePoint, here is [reference](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0).
First you create an app on Azure applications, then assign permissions via Microsoft Graph to read all files (you can find the exact scope name in the `OneDriveHelper`'s `Main.cs` file), I have been successful to create folders, upload files, and move them with this approach, but only when the requests were sent from `Scheduler` assembly. Also when using a standalone instance of RIS it was also working fine, but once I used Quartz.Server, then it would go and throw issue about Newtonsoft not loading...

As for why OneDrive, this was the request from our customer, currently because of this issue they will be using shared folders.

But to be honest, this issue can occur with other type of integration. So I think it's important to review it and make sure it won't cause any other issues with other projects.
