### ISSUE TITLE
 Field mapping data shifts due to cooperation between RIS and D365 Finanace Operations

### ISSUE THREAD

**Issue by keitoyokoi** [microsoft/Recurring-Integrations-Scheduler#116]
#### Expected behavior
CSV data exported from RIS is registered in the field mapped by FO Data Management.

#### Actual behavior
Stop RIS for an hour. After that, when it is started and there are multiple files in the export folder and the multiple files are linked to FO, the mapping shifts.

### Steps to reproduce the problem.
1.Stop RIS Job(Trigger status  Normal →paused)
An hour later...
2.Right-click on the Job and click Open input folder. Place multiple CSV files in it
3.Start RIS Job(Trigger status Paused → Normal)
4.The CSV column that was first imported into FO is misaligned

### Specifications like the version of RIS and platform and application version of D365FO.
RIS version 3.2.2.0
Platform version of D365FO Update36(7.0.5688.35584)
Application version of D365FO 10.0.12 (10.0.507.10024)

**Comment by TomekMelissa** [comment]
I do not quite understand. Is it about export or import. Can you include screenshots?
