### ISSUE TITLE
Integration scheduler with D365 on premise - authentication

### ISSUE THREAD

**Issue by MasRIS** [microsoft/Recurring-Integrations-Scheduler#117]
Can't create service to service authentication - client secret is mandatory

What should be in field "Client secret" when using Service to service authentication via adfs?

**Comment by TomekMelissa** [comment]
An example.
https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/deployment/warehousing-for-on-premise-deployments
