### ISSUE TITLE
C# Compile errors on v1.0.0.0 of the source project

### ISSUE THREAD

**Issue by Anup-Shah** [Microsoft/Recurring-Integrations-Scheduler#12]
### Expected behavior and actual behavior.
I have downloaded the RIS source code, and I am compiling the project in Visual Studio 2015 and I get 14 compile errors. See attached spreadsheet to see all the errors, plus screenshot of error.

I have worked through and declared the Guids as a variable within the project. Once we fix the first 4 errors additional 18 new errors come up.

### Steps to reproduce the problem.
(1) Go to https://github.com/Microsoft/Recurring-Integrations-Scheduler.
(2) Click on "Clone or download" button.
(3) Download and extract the zip file and copy "Recurring-Integrations-Scheduler-master" folder to my \Documents\Visual Studio 2015\Projects.
(4) Open Visual Studio 2015 with Update 3, with elevated priviledges.
(5) Open the RIS solution.
(6) Right-click solution explorer and select Restore NuGet packages.
(7) Right-click solution and build.
(8) Compile errors are thrown.

### Specifications like the version of RIS and platform and application version of D365FO.
RIS v1.0.0.0
![compile error code](https://user-images.githubusercontent.com/28529568/31687673-e32f78ba-b381-11e7-914e-8f9681b33da1.PNG)
[Compile Errors.xlsx](https://github.com/Microsoft/Recurring-Integrations-Scheduler/files/1392510/Compile.Errors.xlsx)

**Comment by jastner** [comment]
Hey there,

I have seen the same behaviour when I started using RIS with VS2015. I had to declar local variables for the "out" variables.

J

**Comment by diegomancassola** [comment]
I have the same problem, the code are written using c#7 standards. You have to use Visual studio 2017 or install the c#7 compiler for visual studio 2015. The code still marked with the red line, but the compiler works good.

**Comment by TomekMelissa** [comment]
Please use Visual Studio 2017. I will add this information to wiki
