### ISSUE TITLE
More than 1 min to upload a file

### ISSUE THREAD

**Issue by ashwinjugurnauth** [microsoft/Recurring-Integrations-Scheduler#120]
Hi Tomek, 

Hope you are doing fine. 

I have noticed a severe degradation of the performance. It takes more than 1 min to upload a file. I think that it might be related to some PU / ADAL. I have downgraded the RIS version and tested previous releases, KO as well. Testing done as follows : 

- Import of 1 package : KO 
- Import of multiple packages : KO 
- Import of flat file : KO 
- Import of multiple flat files : KO 
- Disabling firewall on target machines : KO 

Please reach out if you have some time. 

Cheers
Ashwin

**Comment by TomekMelissa** [comment]
Hi Ashwin,
I cannot repro your report. Everything runs as expected. For some time already RIS is using MSAL by default. You can choose to use ADAL in instance configuration, but I keep it only because MSAL does not work nicely in on-premise scenarios.
