### ISSUE TITLE
Problem with large amount of files

### ISSUE THREAD

**Issue by MasRIS** [microsoft/Recurring-Integrations-Scheduler#124]
We are using RIS for on-cloud environment and we get issue when we have a lot of messages sent from D365FO. While using download job, we see that RIS dequed 1830 files successfully. "Make exported files unique" and "delete package file"  are marked. So after RIS dequed files and probably while trying to unzip, we get an error "RecurringIntegrationsScheduler.Job.Download - Job: Download jobs.InventTableExport. Acknowledgment failure response:  Status: InternalServerError - InternalServerError, Reason: Internal Server Error"
and all packages go to Error Folder. It is not happening when we have 10-20 files to process, but only with large amount of files. Does anyone knows how it can be fixed?

**Comment by TomekMelissa** [comment]
At first sight this error indicates problem on D365 side, not with RIS or unzipping. Please increases logging level to DEBUG in Quartz.Server.exe.config file (assuming you are using RIS service, not its standalone scheduler). Maybe this will indicate some hints on what is going on. 
Why can't you use export job (Package API) for your integration?

**Comment by MasRIS** [comment]
Thank you! Problem was solved by updating data entities in D365 FO
