### ISSUE TITLE
cron expression preventing scheduled.xml from loading

### ISSUE THREAD

**Issue by muehe44** [microsoft/Recurring-Integrations-Scheduler#133]
Hello,
if you add a cron trigger which should run for example twice a day (15:00 / 21:00) it will work. 
<cron-expression>0 0 15,21/12 * * ?</cron-expression>

But if you resart the service, the scheduled.xml file can not be loaded. You will have no jobs in the application anymore.
If you remove now this job from the file, everything works again.

We have this issue with the latest version 3.2.2.0

Best regards
Thomas

**Comment by TomekMelissa** [comment]
hi @muehe44 
I cannot repro this. It works flawlessly with exactly this and any other valid cron expression I tried. Are you sure in your case it is a cron expression that causes the problem? Did you check the event log?
