### ISSUE TITLE
Upload of large file fails with error

### ISSUE THREAD

**Issue by MasRIS** [microsoft/Recurring-Integrations-Scheduler#135]
Hi,
We are trying to upload large file (50 MB) using upload job and get the next error in event log. 
RecurringIntegrationsScheduler.Job.Upload - Job: Upload jobs.Test. Enqueuing failed for file: file1.XML. Failure response: Status:
 RequestEntityTooLarge, Reason: Request Entity Too Large.

Is it limitation from RIS or D365 FO? Is there any way to fix this? We can't use import job cuz we are using xslt transformation in d365fo

Thanks!

**Comment by TomekMelissa** [comment]
It is a limitation of D365. RIS is only a messenger. It does care what you are trying to send.
