### ISSUE TITLE
RIS keeps re-importing same file after 10.0.19 upgrade

### ISSUE THREAD

**Issue by NCardUSVenture** [microsoft/Recurring-Integrations-Scheduler#138]
**Describe the bug**
After upgrading our TEST environment to 10.0.19, we found that the RIS would always upload the same file to DMF.  We can put several different csv files in the input directory for the job, but the file that ends up being imported in DMF is always the same.  We do not see this behavior in UAT, which has not yet been upgraded to 10.0.19.

**To Reproduce**
1. Set up RIS to import files into a 10.0.19 version of Cloud D365
2. Set up an import job and import a csv file into DMF
3. Try to import a different file using the same job
4. Confirm that the originally imported file, not the new one, was imported again in DMF

**Expected behavior**
The same behavior we see in UAT, where the RIS imports the new files into DMF, not the same one over and over.

**Recurring Integration Scheduler version (please complete the following information):**
 - Version 3.2.2

**Dynamics 365 version (please complete the following information):**
 - 10.0.19
 - Update43

**Comment by TomekMelissa** [comment]
Please check eventlog. What the history there shows?
Are we talking about import or upload job?

**Comment by NCardUSVenture** [comment]
These are import jobs.

There are no errors in the event logs, which makes sense since the imports are happening successfully, just with the incorrect file.

One odd thing I noticed in the event logs for the GetDequeueUri and GetRequestAsync calls: the "GUIDs" are just all '0's

RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper - Job: . HttpClientHelper.GetDequeueUri is being called. Output: Generated Uri: https://corptest.sandbox.operations.dynamics.com/api/connector/dequeue/00000000-0000-0000-0000-000000000000

RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper - Job: . HttpClientHelper.GetRequestAsync is being called. Uri: https://corptest.sandbox.operations.dynamics.com/api/connector/dequeue/00000000-0000-0000-0000-000000000000, Parameters: addAuthorization: True

**Comment by TomekMelissa** [comment]
It is an upload job, not an import. I will deploy PU43 and will try to see if something has changed in D365 API. Empty GUID is the reason for what you are experiencing.

**Comment by TomekMelissa** [comment]
Sry, I saw api/connector and I know this is engueue/dequeue API that we call upload/download jobs in RIS.\
But there is one more thing. Those entries are part of download job. When you are downloading files from D365, not uploading to.
Please verify.

**Comment by NCardUSVenture** [comment]
I've attached the version of the Schedule.xml that we made to test just a single import job, which we were using to try to investigate this issue.  Hopefully this clears things up a bit.

[Schedule-SingleJobTest.xml.txt](https://github.com/microsoft/Recurring-Integrations-Scheduler/files/6547169/Schedule-SingleJobTest.xml.txt)

**Comment by TomekMelissa** [comment]
I can see those are in fact import jobs. Then you shared wrong entries from event log.
Please clean RIS event log an try again.

**Comment by NCardUSVenture** [comment]
Tried again.  Even when I checked "Verbose logging", this is the only message that appears in the event log when it does the import:

RecurringIntegrationsScheduler.Job.Import - Job: Import jobs.20USVGeneralJournal. Found 1 file(s) in input folder

**Comment by NCardUSVenture** [comment]
Just wanted to give an update, we migrated to this tool from another third-party tool which we switched back to once this issue arose, and today that tool started to exhibit the same behavior when importing into our upgraded TEST environment.

As a result, we have done some additional testing between our 10.0.19 TEST and 10.0.16 UAT environment with both the RIS tool and our old third-party tool, which both worked perfectly importing files into UAT.

**Comment by TomekMelissa** [comment]
It looks like a regression of D365 in this PEAP release. Expect a fix before the final release of this service update.

**Comment by NCardUSVenture** [comment]
Excellent, that's terrific news.  Thank you very much for investigating this.

Just to be super clear, will the anticipated fix be on the D365 side or the RIS side?
