### ISSUE TITLE
Feature request - import saved schedule file

### ISSUE THREAD

**Issue by NathanDL** [Microsoft/Recurring-Integrations-Scheduler#14]
The tool has the ability to save schedule files, but no functionality to import schedule files that have been previously saved. If this is not on the feature backlog, I would like to request this functionality. 

Ideally (this may be a second feature request), it would be good to be able to load an exported schedule file on startup, from the command line. This would support deployment automation scenarios.

Thanks for your consideration.

**Comment by diegomancassola** [comment]
I'm working on a fork of the project, and yes there is something strange on configuration files:
* App.Config settings are used for debug, but when you run the application it use a config file on AppData folder
* Schedule.xml file can be saved but not restored
* Sometimes the schedule.xml is not loaded automatically by the service.
I will investigate more about this behavior on our fork, but can be good if someone from microsoft give us and hand on that point.

**Comment by TomekMelissa** [comment]
schedule.xml file is only used by scheduler service, not standalone scheduler. Standalone scheduler is only meant for ad hoc imports and exports, so there should be no need to load any particular schedule. 

For deployment automation you can still use custom schedule.xml with some jobs already configured. Scheduler service will always load this file when it starts. The only conditions are that the file is in installation folder of RIS and its xml schema is valid. If you save schedule file using the app it should take care of those conditions.
