### ISSUE TITLE
Package Template to Import Customer Attachments Returns Error "Input file name in Manifest cannot be identified."

### ISSUE THREAD

**Issue by hairulhazri** [microsoft/Recurring-Integrations-Scheduler#141]
**Describe the bug**
I use package template to try importing customer images using Customers V2 attachments entity.
Event viewer returns error "Input file name in Manifest cannot be identified."

**To Reproduce**
1. Input folder contains input txt file, template file, and Resources folder with image files:
![input folder](https://user-images.githubusercontent.com/71490464/125729650-2b75c922-5edc-42a6-8f26-14e0bb90cb8c.PNG)

2. RIS Import job overview:
![import job overview](https://user-images.githubusercontent.com/71490464/125729696-cff96ccf-afab-40f7-8b00-f9c22ef900c6.PNG)

3. RIS Import job detail:
![import job detail](https://user-images.githubusercontent.com/71490464/125729704-89258b2b-9c0a-4cf7-a40c-86033157dc30.PNG)

4. Event viewer:
![event](https://user-images.githubusercontent.com/71490464/125729718-890642a5-8cf3-4683-880c-7954c3e0b23a.PNG)

5. Manifest file:
![manifest file](https://user-images.githubusercontent.com/71490464/125729725-99e9ceaf-a9eb-4bb8-b8dd-b521f597910e.PNG)

**Recurring Integration Scheduler version (please complete the following information):**
 - Version [3.2.2.0]

**Dynamics 365 version (please complete the following information):**
 - Application version 10.0.19
 - Platform version PU43

**Additional context**
Is package template currently does not support importing of attachments?

**Comment by TomekMelissa** [comment]
Importing of attachments is not covered in the simple mechanism of using a package template. You need to create packages yourself , outside of RIS in this case.
