### ISSUE TITLE
I have a download job scheduled in RIS for every one hour and that gets paused automatically in every 5-6 days and I have to resume the job manually to run that again.

### ISSUE THREAD

**Issue by Samarjeet83** [microsoft/Recurring-Integrations-Scheduler#142]
I have a download job scheduled in RIS for every one hour and that gets paused automatically in every 5-6 days and I have to resume the job manually to run that again. I have some upload jobs also scheduled in RIS but that are working fine only upload jobs are getting paused. I have checked the error in event viewer which shows error -
Error-
The description for Event ID 0 from source Recurring Integrations Scheduler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

Quartz.Core.JobRunShell - Job Download jobs.ProdPOLineDownload threw a JobExecutionException:
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False
Quartz.JobExecutionException: Download job: Download jobs.ProdPOLineDownload failed ---> Quartz.JobExecutionException: Job: Download jobs.ProdPOLineDownload. Failure response: Status: BadGateway - BadGateway, Reason: Bad Gateway
at RecurringIntegrationsScheduler.Job.Download.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at RecurringIntegrationsScheduler.Job.Download.d__11.MoveNext()
--- End of inner exception stack trace ---
at RecurringIntegrationsScheduler.Job.Download.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Quartz.Core.JobRunShell.d__9.MoveNext() [See nested exception: Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False
Quartz.JobExecutionException: Job: Download jobs.ProdPOLineDownload. Failure response: Status: BadGateway - BadGateway, Reason: Bad Gateway
at RecurringIntegrationsScheduler.Job.Download.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at RecurringIntegrationsScheduler.Job.Download.d__11.MoveNext()]

As per my expectation,  the download job should not pause automatically once it's has been scheduled.

![RIS Error in event viewer](https://user-images.githubusercontent.com/87299807/126264285-498d7a1e-363a-4970-a710-c93f97b751d6.png)

**Recurring Integration Scheduler version (please complete the following information):**

**Dynamics 365 Finance and Operation
 - Application version - 10.0.16 (10.0.689.20019)
 - Platform version  - PU40

![RIS Error in event viewer](https://user-images.githubusercontent.com/87299807/126265460-45ee14a3-2f6d-47c8-90c1-46768f826d09.png)

**Comment by Samarjeet83** [comment]
Sorry for late response....

Recurring Integration scheduler version is 3.2.2.0

![image](https://user-images.githubusercontent.com/87299807/127640341-05389fd5-a867-4bc9-b703-cfbd04434a02.png)

**Comment by TomekMelissa** [comment]
Bad gateway error in your log points at your Internet connection. It is an indication of some intermittent network problems.
