### ISSUE TITLE
Endless "executing" status, export job no longer works in v3.3.1 via connect to service

### ISSUE THREAD

**Issue by dotjan37** [microsoft/Recurring-Integrations-Scheduler#143]
**Describe the bug**
Endless "executing" status, export job no longer works in v3.3.1

**To Reproduce**
Configure an export job, schedule with "simple trigger" via "Connect to service".
Via "Start standalone scheduler" there is no problem!

**Recurring Integration Scheduler version (please complete the following information):**
 - Version 3.3.1

**Dynamics 365 version (please complete the following information):**
 - Application version 10.0.16
 - Platform version PU40

I don't see anything special in Event Viewer.

With v3.2.2 there is no problem!
With v3.3.1 via "Start standalone scheduler " there is no problem!

**Comment by vukisz** [comment]
Same for import via "Connect to service". Tried for freshly created folder C:\RIS\...
![image](https://user-images.githubusercontent.com/48272340/126630715-407e52ca-2734-4579-9687-33931fe51f83.png)

**Comment by TomekMelissa** [comment]
3.3.0 introduced handling of priority-based throttling. What you observe is most likely this feature in action. D365 throttles RIS requests and delays them. from RIS perspective the job is still active, just waits to repeat the request.

**Comment by dotjan37** [comment]
Hi, TomekMelissa,
I see no job starting with "connect to service" under "Data management" in D365. With "start standalone scheduler" it starts immediately. What the difference? Thanks in advance.

**Comment by TomekMelissa** [comment]
RIS has its Windows service which hosts the scheduler and runs the jobs even after you close RIS app. That is the scheduler you manage when you "connect to service". A standalone scheduler is embedded in RIS main app. It works as long as the application is running. Those two schedulers do not share job configurations. 
In your case first, you need to make sure your RIS windows service is running. Check the account it is running as and verify that there are no restrictions for this account to access the Internet.
Increase logging level for jobs, study event log.

**Comment by vukisz** [comment]
Just FYI 3.2.2.0 was working o.k.
After updating to 3.3.1.0 job execution from service stuck on executing limbo. Nothing happens, no files are being taken from input directory and no information in event viewer.
Trying from start standalone scheduler still works.

**Comment by TomekMelissa** [comment]
Please follow my advice. Switch on verbose logging and show me the event log.

**Comment by vukisz** [comment]
Thanks @TomekMelissa
But this leads to another issue, event viewer is not populating since update:
![image](https://user-images.githubusercontent.com/48272340/128864164-826ba8dc-227a-4f9a-a4d4-ea875c45c3d9.png)

**Comment by TomekMelissa** [comment]
Please uninstall RIS completely. Make sure its folder is empty and Windows service is removed. Then install newest version again.

**Comment by dotjan37** [comment]
Hi TomelMelissa, which event log do you need? I also installed in on a new Windows 10 21H1 installation and v3.3.1 is not working with "connect to service". I set export job with "verbose logging" but i see no logging in event viewer for the time job is planned...

**Comment by vukisz** [comment]
Uninstalled, deleted RIS folder in program files, cleaned all old working folders and installed latest version again. 
Did all setup + job creation. And still same issue that it does not in service mode and no logs are being logged in event viewer with verbose loging.

More detailed steps:
Tested standalone part. All went well
Created similar job in service past. Finished Created new job at ~08:51
It was in non executing status till 08:52. On 08:52 it started executing and stuck in there. On a first minute of execution Next run was automatically set set to 08:53. Input folder was empty.
Few minutes later it still stuck on executing status. And next run was automatically set to 08:50 (don't know why) and since then nothing has changed, still executing and stuck.
What do I miss there?

Screenshot:
![image](https://user-images.githubusercontent.com/48272340/128977267-31e76962-803a-4b58-a9eb-9e1ec56b6fd4.png)

**Comment by VadimGoncharenko** [comment]
In case you are on self-service SF (Tier2 and above) instance of 10.0.21 PEAP version, there is an issue with all export and import jobs getting stuck. The fix promised to be released today

**Comment by dotjan37** [comment]
It's stuck in RIS (connect to service), i tried with a fresh installation of v3.3.1 on new Windows installation in combination with D365 10.0.16 and 10.0.19 PU43, same problem as user vukisz.

**Comment by TomekMelissa** [comment]
I was finally able to repro this. I will try to fix it ASAP.

**Comment by dotjan37** [comment]
Thanks TomekMelissa, with v3.4 it works again

**Comment by vukisz** [comment]
Same for me. Now it works!
Thanks TomekMelissa.
