### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by RobvanB** [Microsoft/Recurring-Integrations-Scheduler#15]
### Expected behavior and actual behavior.
Where can I find information on the expected import format?

**Comment by TomekMelissa** [comment]
You can define the format yourself. See https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-import-export-job

**Comment by RobvanB** [comment]
Thanks for the link, but that doesn't tell me what the RIS application is expecting?
How can I upload .CSV files using this tool? Do I need to convert them into XML first?
If not, how does the tool know which entity to call ?

**Comment by TomekMelissa** [comment]
RIS is unaware of the format. In upload job you need to specify data entity explicitly, in import job you always reference data project where the format is defined. Did you read the wiki?

**Comment by RobvanB** [comment]
ok, I think I understand how it determines the format (based on the data project name in the job data), but I still have some questions (I did read the wiki btw :)  )
From the wiki:
"Package template: Path to package template file (zip archive). When it specified then the import job will zip source files from Input folder into package template “envelope”. Package template (manifest file in it) needs to be in sync with input file format and content. When this field is empty then it is assumed that files in Input folder are already data packages"

So if I drop just a plain CSV file in the input folder, I will need to specify a package template location?
I don't understand what is meant with 'the manifest needs to be in sync with the input file format'.
What is meant with that? What is the manifest?

**Comment by TomekMelissa** [comment]
See this #2
