### ISSUE TITLE
Replace ADAL to MSAL

### ISSUE THREAD

**Issue by DKobayashi-ykgw** [microsoft/Recurring-Integrations-Scheduler#153]
ADAL will EoS in Dec. 2022, so would you re-write AuthenticationHelper.cs using MSAL?

**Comment by TomekMelissa** [comment]
MSAL was introduced and has been a default method since three years already. ADAL is there for on-premise compatibility only.

**Comment by Thangavelan** [comment]
Is there any Latest version of RIS which supports MSAL?

**Comment by DKobayashi-ykgw** [comment]
> MSAL was introduced and has been a default method since three years already. ADAL is there for on-premise compatibility only.

Thanks TomekMelissa,
I confirmed AuthenticationHelper is already using MASL.
