### ISSUE TITLE
Error when importing composites entities

### ISSUE THREAD

**Issue by hectormz87** [Microsoft/Recurring-Integrations-Scheduler#18]
### Expected behavior and actual behavior.
**Expected**: Import done successful
**Actual**: When trying to import a composite entity (vendor invoice journal) an error is showed when the job finish its run
Error message: 
A DataTable named 'VendInvoiceJournalEntity' already belongs to this DataSet.
'0' 'Vendor invoice journal' record(s) inserted in staging
* This is working with no errors with the internal recurring jobs of dynamics 365 for finance and operations
* This is working with no errors with the DIXFSamples in https://github.com/Microsoft/Dynamics-AX-Integration/tree/master/DIXFSamples

### Steps to reproduce the problem.

1. Create an import job with a composite entity like Vendor Invoice Journal.
2. Run the job.
3. Error showed in job in Dynamics
![image](https://user-images.githubusercontent.com/24382318/32351996-f621ce5e-bfe4-11e7-9b76-2cc8417f6670.png)

### Specifications like the version of RIS and platform and application version of D365FO.
Dynamics 365FO: Platform release Update11 (7.0.4679.35180)
Application version: 7.2.11792.56024 

RIS version: 1.0.0 and 1.0.1

**Comment by TomekMelissa** [comment]
Please submit this through MS support. It looks like a bug in package API. Nothing to do with RIS or any other tool of this kind.

**Comment by RobvanB** [comment]
Was this ever resolved? I have the same error with PU12 - direct import with same data project works, RIS throws an error.

**Comment by gprodware** [comment]
Hi,
i am getting the same error for Customer Payment Journal composites entity.

BR,
Gill

**Comment by RomanEder** [comment]
Following up in Yammer: 
https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1147343116
