### ISSUE TITLE
not able to import data using RIS, export work well

### ISSUE THREAD

**Issue by SantoshAvanade** [Microsoft/Recurring-Integrations-Scheduler#19]
### platform version of D365FO is PU9.

![ris import err](https://user-images.githubusercontent.com/33464768/32513092-df41c578-c3ad-11e7-807e-a553cd67cc58.jpg)
![ris import err](https://user-images.githubusercontent.com/33464768/32513097-e5927d0a-c3ad-11e7-97cf-c1b41e1b9708.jpg)

**Comment by TomekMelissa** [comment]
The value for one of the HTTP headers is not in correct format. 
This error occurs for import job run against VM running on downloaded VHD.

**Comment by amitd365** [comment]
This seems a serious issue with no solution. Even I have got the same error. Only suggestion I have got is to change the scheduler.

**Comment by AndreasHassing** [comment]
@SantoshAvanade & @TomekMelissa:
I seem to have run into this issue on a dev box. I solved it by commenting out the `x-ms-version` header in `HttpClientHelper.UploadContentsToBlob`. The version is contained in the SAS token - should I make a PR for this @TomekMelissa?

**Comment by TomekMelissa** [comment]
@AndreasHassing Please do. Good catch!
