### ISSUE TITLE
template.zip example

### ISSUE THREAD

**Issue by Hesel** [Microsoft/Recurring-Integrations-Scheduler#2]
In the wiki there is an image under the Import Job section, which shows a Package Template set to "[...]\template.zip".
Do you have an exampel file which can be used as a Package Template?

I'm unable to figure out how to create a Data Package outside of D365FO. If there is a template used in creating them (and a sort of guide) I would love to see it.

**Comment by JeroenLeeflang** [comment]
See my comment on your question on: https://github.com/Microsoft/Dynamics-AX-Integration/issues/36

**Comment by TomekMelissa** [comment]
1. Create export data project with the same data entity, format, field mappings etc as your target import data project
2. Export data and download data package
3. Delete data file from the package leaving only manifest and header inside zip
4. Copy zip to top folder of your input folder structure
5. Reference that template file in import job settings in RIS.

When you follow this, RIS will take your input file and zip it into template creating data package as a result.
Data project definition will always be overwritten by the definition from manifest file. 

> **Note!** RIS will only pack single data files. It will not work with data projects with multiple data entities *inside*. You need to create such packages on your own. You can still use RIS with those, but you cannot use *package creation* feature.

**Comment by ccampora** [comment]
Tomek, can you explain a littler further? If I am using the DMF API how can start from the data file and add the metadata and zip it on the way? Thank you.
