### ISSUE TITLE
Manage Name and extension when download file

### ISSUE THREAD

**Issue by JJACQUOT** [Microsoft/Recurring-Integrations-Scheduler#20]
Hello, 

When I download a file, it is created with or without date according to the settings and the extension is .tmp.

It's possible to manage the name and extension file? And it's possible to put the date information a the end of the name ?

Example today, I download : 2017-11-21_11-25-23-8689-000001-Customers V2.tmp
And I would like CUSU-2017-11-21_11-25-23-8689-000001.txt

I do not have access to the source code to manage this problem.

Thanks!

Setup Example 

![setup](https://user-images.githubusercontent.com/33906435/33139629-2aa1e2bc-cfae-11e7-9bbb-24dd9e22f649.jpg)

**Comment by TomekMelissa** [comment]
You do have access to source code. This is the line you are looking for. https://github.com/Microsoft/Recurring-Integrations-Scheduler/blob/2cf8c8f7437e62649ed837ffeef780822b594256/Job.Download/Download.cs#L193

**Comment by TomekMelissa** [comment]
Line above sets file name for downloaded package file. Here is where extracted filename is created https://github.com/Microsoft/Recurring-Integrations-Scheduler/blob/2cf8c8f7437e62649ed837ffeef780822b594256/Common/Helpers/FileOperationsHelper.cs#L249
