### ISSUE TITLE
Supporting D365 OnPremise?

### ISSUE THREAD

**Issue by gammelgaard52** [Microsoft/Recurring-Integrations-Scheduler#23]
Has anyone succesfully or partially implemented this with an OnPremise version of D365?
If you have - maby you could elaborate on parts, where you found it tricky?

**Comment by TomekMelissa** [comment]
Support for enqueue/dequeue and package APIs is currently broken in Local Business Data version. There is work in progress to fix that. For the time being RIS or any other integration tool using those API will not work.

**Comment by swidz** [comment]
Does Recurring Integration work in LDB scenario? If not, can we expect in will be available in future? Recurring Integration is not on the list of not implemented features in on-prem.

**Comment by TomekMelissa** [comment]
See statement above. It is not working now (7.3 PU12) You can expect working file-based integration scenarios in LBD version soon. Check [Data Management, Data Entities, and Integrations](https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/inGroup?type=in_group&feedId=13408417&view=all) Yammer group for more info.

**Comment by AndreasHassing** [comment]
@gammelgaard52, @swidz: RIS can work with OnPremise (LBD) now. The [enqueue/dequeue API (recurrence planning by D365FO)](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/recurring-integrations) is not supported, but the [Package API (external recurrence planning)](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-api) is.

Furthermore, the Package API has been extended to allow import of composite data entities, and 
calling `ExportToPackage` is now an asynchronous operation. For more information on how to get these new capabilities, check out https://blogs.msdn.microsoft.com/lcs/2018/04/03/data-integration-capabilities-are-now-available-for-dynamics-365-finance-and-operations-on-premises-deployments/.

**Comment by Shind44** [comment]
Hello,
do you have any news about RIS and OnPremise(LBD) scenario ?

Thanks

**Comment by AndreasHassing** [comment]
@Shind44 what news are you thinking of? It works on LBD - if that's what you're interested in knowing.

**Comment by Shind44** [comment]
Hello Andreas, when you try to use RIS with LBD we have an issue  because it try to use enqueue and this endpoint doesn't work

    "RequestUri": "https://axprj.d365.xxx.fr/namespaces/AXSF/api/connector/enqueue/fb353bfe-3ea0-4604-9fe4-ed44b8e49e03?entity=Interface 01 

-> 404 Not Found

**Comment by AndreasHassing** [comment]
@Shind44 that's because LBD does not support enqueue/dequeue APIs as mentioned [here](https://github.com/microsoft/Recurring-Integrations-Scheduler/issues/23#issuecomment-378918094).

You'll need to use the Package API.

**Comment by Shind44** [comment]
Ok so we need to update code into RIS to use the Package API because RIS use Enqueue API natively

that's right ?

**Comment by AndreasHassing** [comment]
@Shind44 no - RIS already supports the Package API: https://github.com/microsoft/Recurring-Integrations-Scheduler/wiki#configuration-of-scheduler-jobs

**Comment by Shind44** [comment]
Ok great ! that's working
thanks Andreas
