### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by lkett** [Microsoft/Recurring-Integrations-Scheduler#24]
Hi,

since a couple of days a lot of "Bad Request" errors are found in our event logs. In the past we uploaded (and tested) a very lot of files with RIS, so I know it is quite reliable.  When error raising file is added to the queue again it will be processed without errors.
Anyone an idea what issues could possibly result in raising "bad request" errors ?

D365EE PU11
RIS version 7 sept 2017

Thanks in advance

![image](https://user-images.githubusercontent.com/32299366/34818219-7a7c04f6-f6ba-11e7-93f2-3aee332ff9f4.png)

**Comment by RobvanB** [comment]
I have the same problem, but mine does not go through at all, even if I drop the file back in the folder.

**Comment by HerreSch** [comment]
We have actually managed to trace this to a bug in D365FO. One is solved. This caused a second bug that is still in the works. 

The issue occurs if 2 (different) files are loaded at the same time to D365FO. Then a duplicate key is assinged to one of the files and this fails the job. 

There is a work around, by using Cron schedules to schedule the jobs at different times ( we have used 5 second intervals between each job).

**Comment by mtortorice** [comment]
Make sure you're checking the Event View for the Recurring Scheduler and the AX-OData Service for more details. The AX-OData Service logs can be found in Event Viewer under > Applications and Services Logs > Microsoft > Dynamics > AX-OData Service
The underlying issue is probably a missing package template and you can see Martin Drab's solution here: http://dev.goshoom.net/en/2017/10/ris-file-already-exists/

**Comment by HerreSch** [comment]
Mtortorice, unfortunately if it was that easy, it would have been found already. But it is not! Both issues have been recognised as Bugs by MS, that is not saying they have been solved so far, as we still have these issues (especially the second issue).

**Comment by TomekMelissa** [comment]
Nothing to do with RIS it seems. Closing.
