### ISSUE TITLE
Export Job, Event Viewer Error and going to Pause state

### ISSUE THREAD

**Issue by abhishekbaluni** [Microsoft/Recurring-Integrations-Scheduler#26]
### Steps to reproduce the problem.
Export jobs ,  going to Pause state , every now and then 
event viewer  has following erros 

1)  <Data>**RecurringIntegrationsScheduler.Job.Export - One or more errors occurred. System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object. at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at RecurringIntegrationsScheduler.Job.Export.Execute(IJobExecutionContext context) ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()<---**</Data> 

2) 

<Data>RecurringIntegrationsScheduler.Job.Export - Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object. at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Job.Export.<Process>d__5.MoveNext()</Data> 

### Specifications like the version of RIS and platform and application version of D365FO.
D365FO - platform 9
RIS : 1.0.1.0

**Comment by AndreasHassing** [comment]
This _could_ be caused by a corner case issue.

When D365FO is exporting, it may report "Succeeded" before the download package is available. RIS attempts to download the package right away even though the download URL may be an empty string (since the package is not yet ready).

**Comment by abhishekbaluni** [comment]
Thank you Andreas, for taking the time to review this.  
the export jobs I have a simple trigger set to run every hour ,  there are about 6 of them, and randomly every 2-4 hours , I will have a 2-3 jobs in the paused state , frequent enough
here is the sequence of errors in the event viewer 

1) RecurringIntegrationsScheduler.Job.Export - Job: Test Export.06 Test job was paused because of error
2)
_RecurringIntegrationsScheduler.Job.Export - One or more errors occurred.
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.    at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()_

3) _RecurringIntegrationsScheduler.Job.Export - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.   RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<GetExecutionSummaryStatus>d__19.MoveNext()_



1) I will download the latest RIS , and see if that helps , trying to avoid the situation where an admin going into the server , resume the jobs that have been paused , every 2-3 

2) is there a way we can reset the paused jobs back to Resume, config setting,  or not pause the job at all on exception
