### ISSUE TITLE
Untrusted connection issues

### ISSUE THREAD

**Issue by danz1ka19** [Microsoft/Recurring-Integrations-Scheduler#3]
Cannot establish a connection to AOS using RIS. RIS indicates that the certificate is untrusted for the SSL/TLS connection establishment.
I am running AX7 update 8, and would like to know how to establish a service to service end point communication between the AOS and the client

**Comment by TomekMelissa** [comment]
Please double check you configuration. Where do you see this error? In Event Log or during validation of an instance?

**Comment by danz1ka19** [comment]
The config is fine and works like a charm on VM. If I try to use actual OS to connect to the AOS then the connection gives an error indicating "cannot establish SSL/TLS connection because the client doesn't trust the connection".

**Comment by TomekMelissa** [comment]
Are you trying to connect to AOS instance on your VM? Can you access this instance in standard way (browser) from your local computer (actual OS)? If not then you need to explicitly trust VM's SSL certificate.

**Comment by danz1ka19** [comment]
I can access the AOS via browser on my local computer.
The problem lies in self-signed certificate. It has to generate a certificate using a certified trusted root authority.
