### ISSUE TITLE
Incorrect file format error - intermittent

### ISSUE THREAD

**Issue by HerreSch** [Microsoft/Recurring-Integrations-Scheduler#33]
Hi, 

we have created a recurring interface with RIS and it is working great for the most part, however sometimes, (once a day on average (and we load 100+ files per day over 5 10 differnt jobs) we get an error saying

XML is not in correct format-
'0' 'Sales tax exempt numbers' record(s) inserted in staging

However when we reprocess the exact same XML the file is uploaded and processed without any issue. 

We have already changed the delivery of the XML (long time ago) to first put the file in the input folder with a TMP extenstion. When the file is completed, we change the extension to XML and that should then be loaded. 

We have not been able to narrow down the issue any further. It almost seens like the file is picked up when not fully finished, however we not understand how this is possible if we write the file and then rename to XML after it has been written fully. Below our settings of one of the jobs. 

![image](https://user-images.githubusercontent.com/38351705/38733871-e2e5fcac-3f23-11e8-827a-5db506f31225.png)

Thanx 
Herre

**Comment by AndreasHassing** [comment]
Have you tried getting the file into a folder that is not being watched by RIS, and Then do the renaming, and Then move the file to the Input folder?

I'm not sure if 'XML is not in correct format' is referring to the extension of the file, or the actual contents of the file. Maybe you should try and examine the XML in the files that fail processing, and validate that it is in fact valid XML.

**Comment by TomekMelissa** [comment]
I would recommend to inspect uploaded file, but it ain't easy. You would need access to shared blob storage. You can try it on your sandbox...
Is your input folder a file share? Files are copied and renamed by some remote computer/service?
Can you try to process those files in different folder and only move them to input folder when they are complete and ready?

**Comment by HerreSch** [comment]
Tomek, it is always on the same server. We use a local server, do the transformations we require and then rename to XML. 

If on a sandbox, how could I find the uploaded file? I am not even sure how to get into the blob storage. 

I will see if we can change the logic. However with the setup I would expect RIS to only process files that are called XML?
