### ISSUE TITLE
Unexpected error : Error communicating with remote scheduler

### ISSUE THREAD

**Issue by JJACQUOT** [Microsoft/Recurring-Integrations-Scheduler#34]
### Specifications like the version of RIS and platform and application version of D365FO.

Hi,

I have download the new version 2.0.1 and i have an error message when I want to save a download job to add : "Unexpected error : Error communicating with remote scheduler".

![img1](https://user-images.githubusercontent.com/33906435/38743350-29402de2-3f3f-11e8-85a4-77e48a1ad429.png)

Thanks!

**Comment by JJACQUOT** [comment]
It looks like we need a 64-bit?

**Comment by TomekMelissa** [comment]
I cannot repro this. Could you provide more details of your environment? Are you sure scheduler service is not blocked by firewall or any other AV solution? Why are you mentioning 64bit?

**Comment by MZade** [comment]
@jjacquot, I see this happens if the RIS Service is stopped. May be it is the case?

**Comment by TomekMelissa** [comment]
Yes, that is the case. If you choose to work with scheduler service then it needs to be running all the time.
