### ISSUE TITLE
[Enhancement request] Custom OData action endpoint relative path

### ISSUE THREAD

**Issue by MZade** [Microsoft/Recurring-Integrations-Scheduler#36]
### Expected behavior and actual behavior.
This is an **enhancement request** to have customizeable OData action endpoints as in some cases it is usefull to be able to have custom services which can be used to communicate with instead of the D365FO standard one. In my current project we do use this approach by customizing the RIS codebase and I see an opportunity to have this included in the RIS codebase to avoid double maintenance of the solution. I'll be able to help on this point after alignment about the design considerations to make the merging back to the RIS codebase as smooth as possible. Please contact me back to discuss the idea.

### Steps to reproduce the problem.
N/A
### Specifications like the version of RIS and platform and application version of D365FO.
N/A

**Comment by TomekMelissa** [comment]
Thanks Mehrdad. As I mentioned in this #32 in my opinion custom path should be part of job configuration. That means included on configuration forms and handled the same way as the rest of job parameters. This gives you more flexibility. 
For the start it will be enough to implement it for two actions: ImportFromPackage and ExportToPackage

**Comment by MZade** [comment]
@TomekMelissa , Nice...I'll launch the pool request soon...

**Comment by TomekMelissa** [comment]
Hi @MZade, I released new version with those changes (and some modifications) Can you please verify that?

**Comment by TomekMelissa** [comment]
Resolved with #32

**Comment by MZade** [comment]
Hi @TomekMelissa, We are curently testing the solution and so far so good. 
Thanks to have this effort together, as our current project is getting in the code frees periode (next week), it was important to act fast and we are glad to have the required features in the master branch. 
Thanks!

**Comment by MZade** [comment]
Hi @TomekMelissa, Seems to work fine

![image](https://user-images.githubusercontent.com/19854220/39070734-cb6f5b56-44e4-11e8-9067-b28bb31e6999.png)
