### ISSUE TITLE
Some errors showing up when using the Validate instance settings form

### ISSUE THREAD

**Issue by MZade** [Microsoft/Recurring-Integrations-Scheduler#39]
### Expected behavior and actual behavior.
Related to https://github.com/Microsoft/Recurring-Integrations-Scheduler/releases/tag/v2.1.0

Some errors showing up when using the Validate connection.
This can be solved by the following pull request: https://github.com/Microsoft/Recurring-Integrations-Scheduler/pull/38

### Steps to reproduce the problem.
**Screenshot of the error**
![image](https://user-images.githubusercontent.com/19854220/39051744-f6d8671e-44a9-11e8-8657-8b7f94e0d189.png)

**Comment by TomekMelissa** [comment]
Resolved with 07094db8fdb5e4de466d963a61f8ce13fc6b0aab
