### ISSUE TITLE
"Unexpected error" pop-up window

### ISSUE THREAD

**Issue by buttsj** [Microsoft/Recurring-Integrations-Scheduler#4]
### Problem
![image](https://user-images.githubusercontent.com/10159810/31018750-2b14ca8a-a4fb-11e7-99ae-3a0a543ae986.png)

I get this error window that continues to pop up until I restart the application. Happens when there are >2 jobs in the scheduler and I delete one.
### Steps to reproduce the problem.
Create multiple jobs, pause them, and delete one. Then try refreshing the app jobs.

**Comment by TomekMelissa** [comment]
Cannot repro this behavior. Could you write exact repro steps? Especially where the focus on the grid is, when you click "Delete job".
