### ISSUE TITLE
Custom Odata actions of execution summary actions are not saved in Schedule.xml

### ISSUE THREAD

**Issue by MZade** [Microsoft/Recurring-Integrations-Scheduler#40]
### Expected behavior and actual behavior.
The following two values need also to be saved and retrieved from the Schedule.xml

![image](https://user-images.githubusercontent.com/19854220/39181787-0bde95c0-47bb-11e8-8633-2cfe8715f64f.png)

The issue might be related to the fact that these settings are added to the implementation of the method:
 private JobDataMap GetExecutionJobDataMap()

### Steps to reproduce the problem.
Adjust these values, save the schedule.xml file and load the job settings again by closing and reopenning of the job details.

### Specifications like the version of RIS and platform and application version of D365FO.
RIS version 2.1.1
https://github.com/Microsoft/Recurring-Integrations-Scheduler/releases/tag/v2.1.1

**Comment by TomekMelissa** [comment]
Those two actions are only used by Execution monitoring job. I decided to store them in execution monitoring job definition. If your import job will not schedule execution monitoring job as well then those settings will not be saved, but at the same time they will not be used anywhere.

**Comment by MZade** [comment]
Hi @TomekMelissa , Thanks for the clarification. 
I have verified this scenario and can confirm that it is indeed getting stored in the schedule.xml

Thanks!
