### ISSUE TITLE
[Enhancement request] Save jobs settings after closing the client

### ISSUE THREAD

**Issue by skaue** [Microsoft/Recurring-Integrations-Scheduler#43]
V 2.2.0
Let us save the export/import jobs settings when testing the client, so any configuration is not lost.

**Comment by MZade** [comment]
Hi @TomekMelissa, 
How do you see such a requested feature should look like to? 
Should there be a menu button which enables you to import the job definitions from a Schedule.xml file i.e. ? Or it should automatically begin importing the latest jobs where you busy with once you start the stand-alone instance through the user interface? Or?

**Comment by AndreasHassing** [comment]
@MZade those two ideas are not mutually exclusive. Implementing both would be ideal 🙂.

**Comment by TomekMelissa** [comment]
Please have a look at v.2.3.0 release
