### ISSUE TITLE
Upload Job

### ISSUE THREAD

**Issue by vaiskhaleghi** [Microsoft/Recurring-Integrations-Scheduler#44]
### Expected behavior and actual behavior.
Upload Job
### Steps to reproduce the problem.
filled up needed parameters and tested connections which were successful. 
make an upload job with XML file inserted my file into an input folder and it was processed and moved to the successful folder.
Nothing gets processed on AX side of things and when I look at the logs the correlationID is null which i thought should be filled in my experience. 

All the parameters filled correctly with correct job ids and service authentication

Screenshot of the connection test getting an error at the bottom.
![image](https://user-images.githubusercontent.com/15386144/39764630-0adc2522-52ae-11e8-9a50-110ac4d11b6b.png)

### Specifications like the version of RIS and platform and application version of D365FO.
Latest version

**Comment by TomekMelissa** [comment]
Upload job only uploads file to D365FO. Message is saved in data job queue. Associated data job's batch job needs to run on some schedule to fetch uploaded messages and process the import. 
Import job works with package API and uploads and starts import immediately.

**Comment by vaiskhaleghi** [comment]
I understand the process behind the upload job but I'm trying to import single XML file and unable to do so. Does the upload process ONLY work with package API?
