### ISSUE TITLE
[Enhancement request/Issue] Job Paused status gets forgotten after restart of scheduler

### ISSUE THREAD

**Issue by MZade** [Microsoft/Recurring-Integrations-Scheduler#45]
### Expected behavior and actual behavior.
After restarting the RIS Service and/also RIS Standalone service the jobs that were set to Paused will be set back to status Normal.
The expectation is once a job is set to Paused that it stays in this Paused status.

### Steps to reproduce the problem.
Start RIS client app
Start standalone scheduler
Add i.e. an Import job
Change the status to Paused
Close the RIS client app
Start the RIS client app again
Start the standalone scheduler again
You will see that the job status is set to Normal...instead of on the last set status which was "Paused"
The same can be reproduced by using the RIS background scheduler

### Specifications like the version of RIS and platform and application version of D365FO.
RIS 2.3.0 and earlier versions having this issue.

**Comment by TomekMelissa** [comment]
Technically speaking we are talking about status of triggers not jobs... When scheduler starts it reads jobs and triggers config from XML file. Your requests means that we should save this entier file (Schedule.xml or Standalone_schedule.xml) everytime we pause/resume any job.

**Comment by MZade** [comment]
Well, I think the best way is indeed to store the trigger status of the triggers that get in status paused by the user intentionally; at least at the moment the scheduler goes down(/existing) and retrieve this when we start again to prevent triggering of jobs where their triggers are set to paused by the user.

**Comment by TomekMelissa** [comment]
After a bit of digging into quartz.net i found out there is unfortunately no way to store paused status (or any status) of a trigger in schedule file. It is possible to add job without the trigger at all, but that would require more effort to implement in RIS that I anticipated and could only cause confusion among users...
I propose instead to implement interactive loading of a schedule file. This would enable scenario where you have multiple schedule files with different set of jobs that you could reuse at will.

**Comment by MZade** [comment]
Do you think, is it possible to elaborate with Quartz.net team to have the possibility of storing the paused status of triggers ?

**Comment by MZade** [comment]
The idea to have multiple schedule.xml files and allow the user to choose which one to be used is a good workaround. 

But I think it is a very natural reaction/expectation, if we say when the user sets a job in paused (=stopped) it should stay in paused status; even if the application is restarted in the meantime. Otherwise when an unintended restart happens the jobs may spring back to action while this might not always be the expected behavior.

**Comment by MZade** [comment]
Hi @TomekMelissa, I see when i.e. an "Export job" is created, initially it gets in status "Blocked"; And if i restart the App without resuming this newly created job...after the restart of the App the job is still in status "Blocked".
May we not give the use the opportunity to "Block" the jobs manually whenever the user wants to prevent further execution of a given job ?

**Comment by MZade** [comment]
Hi @TomekMelissa, Do we have any changes related to #45?

**Comment by TomekMelissa** [comment]
Nope and I do not plan anything.

**Comment by MZade** [comment]
Thanks for the update. 
Would be great if we might reconsider this in the future
..it is especially useful when you have lots of jobs and do not want to loos the definition of them..but also do not want to let them run each time. 
This happens a lot during project implementation if we use the data management framework for integration purposes (especially for export jobs that are working against data projects with incremental push settings)

**Comment by lahma** [comment]
Little late in to the game here I guess, but the natively supported solution in Quartz.NET to pause trigger persistently is using persistent job store (AdoJobStore). This can even be SQLite database for the least friction if you don't want to set up full-blown relational database instance.

You can pause specific triggers or groups. You can pause a job but that basically checks what triggers are associated with the job at the given moment and pauses the triggers.
