### ISSUE TITLE
RecurringIntegrationsScheduler.Job.Import - Job: Import.ajajajaj. Upload failed for file: C:\Users\ajk\Documents\RecurringJobD365\In\Input\testimport.zip. Failure response:  Status: BadRequest, Reason: Bad Request

### ISSUE THREAD

**Issue by sumadhuram456** [Microsoft/Recurring-Integrations-Scheduler#47]
Hi,

I tried to to schedule Add import job(Recommended way) as shown below
(I am able to successfully validate the connection to D365)

I tried providing .zip files in my input folder. 
There are multiple issues here after processing. 
1) As per the description given, if data project does not exist, it will create one in D365. but it did not create any data project with the name i provided. sample zip file i used is 
[test.zip](https://github.com/Microsoft/Recurring-Integrations-Scheduler/files/2032295/test.zip)

2) when I checked the event viewer, i got below error
RecurringIntegrationsScheduler.Job.Import - Job: Import.ajajajaj. Upload failed for file: C:\Users\ajk\Documents\RecurringJobD365\In\Input\test.zip. Failure response:  Status: BadRequest, Reason: Bad Request

can you please help what is going wrong here

![image](https://user-images.githubusercontent.com/25096417/40442090-689eebc0-5ee0-11e8-8143-9b27c3cc8cee.png)

**Comment by TomekMelissa** [comment]
Your zip contains folder with files. Archive files only - without folder

**Comment by sumadhuram456** [comment]
Thank you very much. It works now :)
