### ISSUE TITLE
Validation form produces errors

### ISSUE THREAD

**Issue by bjornmicallef** [Microsoft/Recurring-Integrations-Scheduler#49]
I downloaded this solution in an attempt to connect to my D365FO instance. Managed to run it locally and set up parameter. When I try to run the Validate process I am getting the following errors. Debugged the solution and the first error turns out to be a HTTP 302 error. This happens when I try to send an async request to the AOS URL. The auth bearer token is being sent with the request.

I am also getting 401 Unauthorized error right after when hitting the DequeueUri and when executing the AzureWriteUrl request. Any ideas why I'm getting these error?

Thanks in advance.

![ris01](https://user-images.githubusercontent.com/31951436/41719978-8968cfd0-7559-11e8-93bc-aaa254320096.JPG)

**Comment by TomekMelissa** [comment]
Looks like really old version or you made a mistake in AOS url. it should be sandbox.operations.dynamics.com. 
Also did you map AAD app to a user?

**Comment by bjornmicallef** [comment]
This is what I got. Don't know whether the URL should or should not have the sandbox.ax.dynamics but it seems to be working for me with the sandbox.ax.dynamics.

![ris02](https://user-images.githubusercontent.com/31951436/41728177-0a7196f2-756e-11e8-849c-08c5782ff377.JPG)

I have registered the D365 on AAD and I have an owner assigned to it, if it answers your question

![ris03](https://user-images.githubusercontent.com/31951436/41728862-bef5b346-756f-11e8-80d6-4c59c7ce4ed3.JPG)

Similarly I have registered the AAD app on the D365. Client ID matches and the user I'm using to sign in on the D365 has the same email address as the owner on the AAD app.

![ris04](https://user-images.githubusercontent.com/31951436/41728962-fc6b5168-756f-11e8-9a6d-d0b4fb23fa50.JPG)

**Comment by TomekMelissa** [comment]
Looks like you registered service to service app and then you are using it with user auth flow. Please follow the wiki. Use S2S app with secret or native app with user.

**Comment by RussKuksin** [comment]
Ax 8.0 PU15 - same issue
![image](https://user-images.githubusercontent.com/43584248/46316610-e94d0680-c58d-11e8-82c5-2f580a508a3e.png)

The application is registered in AAD according to wiki and connected in AX side as well.
Any advise?

Thank you,
Russ

**Comment by TomekMelissa** [comment]
What is happening when you try to use it in one of the jobs?

**Comment by RussKuksin** [comment]
It attempts to run, finds one file I am using currently for test, trying to wrap it as package and then fails with this:
![image](https://user-images.githubusercontent.com/43584248/46352528-4345de80-c617-11e8-8d0b-4d6d577ea4e3.png)

**Comment by RussKuksin** [comment]
Ok, I finally got some time and did some debugging around the connection validation code with the HttpClientHelper and got some interesting results which, being not a Web developer, I am not sure how to interpret.

The first thing the validation code does is an attempt to get result from running "GetRequestAsync" with the AOS uri provided as its parameter. If no errors were thrown during that the next thing we see is "Authentication was successful!" phrase and after that some analysis of the StatusCode results. 
The expected response code is to be "200" or "OK", but in my case the result code is actually "302" or "Redirect". I did quick analysis of our AOS standard response using "https://httpstatus.io/" service and found that it does "302->302->200" sequence every time, the first being to "https://login.windows.net" second to "https://login.microsoftonline.com" and third good response.

Now continuing with validation sequence the next step is to attempt the "Dequeue" call with use of empty guid for the ActivityID. The validation code seems to assume that by this point we are successfully authenticated and therefore only checking for responses to be either "Forbidden" or "InternalServerError", but in our case this call actually returns with 401 - "Unauthorized".

It is clear now that the authentication is not complete by the time when the specific call attempts are done, but I am not sure yet why or where and how to fix it.
Any guidance will be greatly appreciated.

Thank you,
Russ

**Comment by TomekMelissa** [comment]
Validation part is not really reliable... I am considering removing it if I cannot provide reliable results in all scenarios.
Try run simple export job and tell me if it is working.

**Comment by RussKuksin** [comment]
Just made the simple download test, ran and here is the result in the event viewer:
![image](https://user-images.githubusercontent.com/43584248/47035604-ad8e7100-d137-11e8-939e-32e6c5e351fd.png)

As you see it is showing the same issue: "Download failure. Unauthorized."

**Comment by TomekMelissa** [comment]
did you map your app with a user in D365?

**Comment by RussKuksin** [comment]
Yes I did. That is part of the instruction and I saw some people struggled
with this part missing, so I checked and rechecked it several times.

**Comment by TomekMelissa** [comment]
and permissions for the ERP are set in AAD configuration as described here https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page

**Comment by RussKuksin** [comment]
Yep. Have read that article. Here is what I have as my settings:
![screen 1](https://user-images.githubusercontent.com/43584248/47096286-17685280-d1ec-11e8-889f-7f726cfb823a.PNG)
![screen 2](https://user-images.githubusercontent.com/43584248/47096295-19caac80-d1ec-11e8-89a3-62d921317384.PNG)

I have downloaded the "ServiceSamples" code from GitHub which has separate examples for the OData access and has the authentication test and fooled around with it. So far as I understand the AAD authentication is going through like it should and the "Unauthorized" is the AX response like it does not recognize the Azure app registration with the admin account...
![screen 3](https://user-images.githubusercontent.com/43584248/47096433-6c0bcd80-d1ec-11e8-9661-c2d0910189cd.PNG)

I assume as soon as I can resolve this problem the rest will just work, but I am out of ideas. Everything seems to be setup as described in all the documentation.

**Comment by RussKuksin** [comment]
Ok, the problem seems to be in the weird AAD tenant setup on our side. 
I have been able to successfully authenticate and have access to the OData but only on one specific AX box with only one specific account mapped to the azure application. Every other combination is either replied with "Unauthorized" or "Forbidden".

Sorry for all the noise.

Russ
