### ISSUE TITLE
Import job - missing add schedule button

### ISSUE THREAD

**Issue by fhburney** [Microsoft/Recurring-Integrations-Scheduler#50]
I am having a weird issue, I have installed the latest version of the tool.

When I do Add import job, I do not get the add schedule and cancel button on the screen. so I am unable to add import jobs and also to exit I have to kill it from task manager.

Any ideas?
![addschedule](https://user-images.githubusercontent.com/28990985/42056734-0736485e-7ad0-11e8-977d-098058e3df9e.png)

**Comment by MZade** [comment]
It has to do with your screen resolution. Try to change it and restart the App.

**Comment by fhburney** [comment]
Thanks!, I downloaded the source code and the .dlls and figured out it was a resolution thing. 
I might just make that screen a little bigger and generate the installer file for it.

**Comment by MZade** [comment]
Yes indeed. I had fixed and checked it in once in the past. But then the next developer was working apparently with a better screen than me and modified it back. The dependency to resolution is not always a good idea...

**Comment by fhburney** [comment]
This fixed it. I allowed the window to be resized
![image](https://user-images.githubusercontent.com/28990985/42183809-096a160c-7df8-11e8-8317-e2fb787257e8.png)

**Comment by fhburney** [comment]
with the latest build, i do not have this issue.
