### ISSUE TITLE
 System.MissingMethodException: method not found: '!!0[] System.Array.Empty()'.

### ISSUE THREAD

**Issue by Mariano1978** [Microsoft/Recurring-Integrations-Scheduler#51]
I'm currently using D365 8.0 PU15, I've created a new composite data entity that it's working fine if I process it manually, I've setup the scheduler application but when it process the job an error is thrown, in the event viewer I can see the detail, but I'm not able to see what is the problem:

Quartz.Core.ErrorLogger - Job Import.VIJ_CGC2012 threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   in RecurringIntegrationsScheduler.Job.Import.Execute(IJobExecutionContext context)
   in Quartz.Core.JobRunShell.Run()
   --- End of stack trace of internal exception --- [See nested exception: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
  in RecurringIntegrationsScheduler.Job.Import.Execute(IJobExecutionContext context)
   in Quartz.Core.JobRunShell.Run()]

The job fails if I create it as a import job, but if I create it as a upload job it works.

I found the problem, it is needed 4.6 .net framework version to run the application, the wiki should be update as it says 4.5 is needed to use the application.

**Comment by TomekMelissa** [comment]
Could you send me your input file and package template you are using?
I will update the wiki. Thanks for pointing that.

**Comment by Mariano1978** [comment]
I found the problem, it is needed 4.6 .net framework version to run the application, the wiki should be update as it says 4.5 is needed to use the application.
