### ISSUE TITLE
Bad request.

### ISSUE THREAD

**Issue by easywithD365** [microsoft/Recurring-Integrations-Scheduler#54]
I created own setup  of RIS is which is of size 1212kb smaller than setup 1447 kb downloaded from GitHub. Is there something wrong ?

###my customized RIS installed successfully. Source code version v.2.3.0.
### Import recurring job is throwing following error. I have using recommended job options only.

The description for Event ID 0 from source Recurring Integrations Scheduler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

RecurringIntegrationsScheduler.Job.Import - Job: Import jobs.Import Customer Groups CSV. Upload failed for file: C:\Integrations\Inbound\Input\Customer groups.csv. Failure response:  Status: BadRequest, Reason: Bad Request

--------------------------------------------------------------------------------
i can see status file under C:\Integrations\Inbound\UploadErrors

**Comment by mtortorice** [comment]
See Martin Drab's solution here: http://dev.goshoom.net/en/2017/10/ris-file-already-exists/

**Comment by easywithD365** [comment]
checked Martin Drab's solution suggested by you. I didn't find any file basically in temp folder.
i checked event logs & it's shows below error message:

**Error No.  1**

+ System 

  - Provider 

   [ Name]  Microsoft-Dynamics-AX-ODataService 
   [ Guid]  {DB19142A-6CD4-4C87-BAFB-9DFE55552F9D} 
 
   EventID 24 
 
   Version 0 
 
   Level 2 
 
   Task 18 
 
   Opcode 0 
 
   Keywords 0x4000000100000004 
 
  - TimeCreated 

   [ SystemTime]  2018-07-18T09:07:22.921580400Z 
 
   EventRecordID 533559 
 
  - Correlation 

   [ ActivityID]  {FCD07519-1E68-0007-A188-D0FC681ED401} 
 
  - Execution 

   [ ProcessID]  2740 
   [ ThreadID]  9652 
 
   Channel Microsoft-Dynamics-AX-ODataService/Operational 
 
   Computer MININT-F36S5EH 
 
  - Security 

   [ UserID]  S-1-5-20 
 

- EventData 

  ComponentName ODataService 
  exceptionMessage System.InvalidOperationException: Exception occurred while executing action ImportFromPackage on Entity DataManagementDefinitionGroup: Could not find file 'C:\windows\TEMP\CDD33EE2-3489-4A41-832D-4BC1B6E4132D_67E82A39-C5EF-4ADC-AF50-204E647563B2\PackageHeader.xml'. at Microsoft.Dynamics.Platform.Integration.Services.OData.Action.ActionInvokable.Invoke() at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateProcessor.ActionInvocation(ChangeOperationContext context, ActionInvokable action) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.<>c__DisplayClass13_0.<ScheduleInvokable>b__0(ChangeOperationContext context) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActionsInCompanyContext(IEnumerable`1 actionList, ChangeOperationContext operationContext) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActions(ChangeOperationContext context) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.SaveChanges() at Microsoft.Dynamics.Platform.Integration.Services.OData.AxODataDelegatingHandler.<SaveChangesAsync>d__2.MoveNext() 
  infoMessage An exception occured while calling SaveChanges on the UpdateManager. 


**Error No.  2**

- System 

  - Provider 

   [ Name]  Microsoft-Dynamics-AX-ODataService 
   [ Guid]  {DB19142A-6CD4-4C87-BAFB-9DFE55552F9D} 
 
   EventID 21 
 
   Version 0 
 
   Level 2 
 
   Task 15 
 
   Opcode 0 
 
   Keywords 0x4000000100000004 
 
  - TimeCreated 

   [ SystemTime]  2018-07-18T09:07:22.920713100Z 
 
   EventRecordID 533557 
 
  - Correlation 

   [ ActivityID]  {FCD07519-1E68-0007-A188-D0FC681ED401} 
 
  - Execution 

   [ ProcessID]  2740 
   [ ThreadID]  9652 
 
   Channel Microsoft-Dynamics-AX-ODataService/Operational 
 
   Computer MININT-F36S5EH 
 
  - Security 

   [ UserID]  S-1-5-20 
 

- EventData 

  ComponentName ODataService 
  exceptionMessage Exception occurred while executing action ImportFromPackage on Entity DataManagementDefinitionGroup: Could not find file 'C:\windows\TEMP\CDD33EE2-3489-4A41-832D-4BC1B6E4132D_67E82A39-C5EF-4ADC-AF50-204E647563B2\PackageHeader.xml'. 
  infoMessage Action invoked failed.

**Comment by TomekMelissa** [comment]
could you show screenshot of your template's content (files in zip archive)

**Comment by mtortorice** [comment]
Make sure you follow the step to export the Package file from the Data Project and add it to your Scheduler Job.

![image](https://user-images.githubusercontent.com/230686/42886319-e022a4ee-8a68-11e8-8216-e49435a5fe17.png)

**Comment by SwathySubramani** [comment]
@easywithD365 , I am trying to use RIS (version 2.7.1)  with D365 F&O On-Premises ( D-10 PU24) facing the same issue. 

Files are moved to error folder after processing the import job.

Find below the setup done for Import Job.

![image](https://user-images.githubusercontent.com/50476895/58623961-bc9fe900-82ec-11e9-873e-1720dbd0f946.png)

As per the error log, the authentication is sucessful and post the request URI for ImportFromPackage , the status code is set to false.

**Error File Log :** 
"IsSuccessStatusCode": false 

The request uri is, https://[baseURL]/namespaces/AXSF/data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.ImportFromPackage


**Event log Error:**
![RIS_ImportErrorLog](https://user-images.githubusercontent.com/50476895/58625031-33d67c80-82ef-11e9-9d23-d35f125d22d4.png)


Kindly suggest.

**Comment by DarkSmile92** [comment]
We are experiencing the same problem with version `2.7.1.0` but a cloud prod system:

```json
{
  "Version": {
    "Major": 1,
    "Minor": 1,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "Content": {
    "Headers": [
      {
        "Key": "Content-Length",
        "Value": [
          "1425"
        ]
      },
      {
        "Key": "Content-Type",
        "Value": [
          "application/json; odata.metadata=minimal"
        ]
      }
    ]
  },
  "StatusCode": "BadRequest",
  "ReasonPhrase": "Bad Request",
  "Headers": [
    {
      "Key": "OData-Version",
      "Value": [
        "4.0"
      ]
    },
    {
      "Key": "ms-dyn-fqhn",
      "Value": [
        ""
      ]
    },
    {
      "Key": "ms-dyn-namespace",
      "Value": [
        "AxProdProd"
      ]
    },
    {
      "Key": "ms-dyn-tenant",
      "Value": [
        "****"
      ]
    },
    {
      "Key": "ms-dyn-role",
      "Value": [
        ""
      ]
    },
    {
      "Key": "ms-dyn-aid",
      "Value": [
        "****"
      ]
    },
    {
      "Key": "X-Content-Type-Options",
      "Value": [
        "nosniff"
      ]
    },
    {
      "Key": "X-Frame-Options",
      "Value": [
        "SAMEORIGIN"
      ]
    },
    {
      "Key": "Strict-Transport-Security",
      "Value": [
        "max-age=31536000; includeSubDomains"
      ]
    },
    {
      "Key": "Date",
      "Value": [
        "Tue, 14 Jan 2020 08:21:17 GMT"
      ]
    },
    {
      "Key": "P3P",
      "Value": [
        "CP=\"No P3P policy defined.  Read the Microsoft privacy statement at https://go.microsoft.com/fwlink/?LinkId=271135\""
      ]
    },
    {
      "Key": "Server",
      "Value": [
        "Microsoft-IIS/10.0"
      ]
    }
  ],
  "RequestMessage": {
    "Version": {
      "Major": 1,
      "Minor": 1,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    "Content": {
      "Headers": [
        {
          "Key": "Content-Type",
          "Value": [
            "application/json; charset=utf-8"
          ]
        },
        {
          "Key": "Content-Length",
          "Value": [
            "431"
          ]
        }
      ]
    },
    "Method": {
      "Method": "POST"
    },
    "RequestUri": "https://****.operations.dynamics.com:443/data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.ImportFromPackage",
    "Headers": [
      {
        "Key": "Authorization",
        "Value": [
          "Bearer ****"
        ]
      },
      {
        "Key": "Accept",
        "Value": [
          "application/json"
        ]
      }
    ],
    "Properties": {}
  },
  "IsSuccessStatusCode": false
}
```

**Comment by TomekMelissa** [comment]
Did this job worked before?
Did you validate that your package structure is valid? Nothing has changed in data entities?

**Comment by DarkSmile92** [comment]
I exported the package again just to be sure. There are multiple jobs (one for each legal entity with different folder paths) and some work but some produce this error. There is no pattern because it's not always just the same that are failing.
So sometimes the job works, sometimes not.

How can I provide more details to find a solution? For exmaple where can I start to look to get more information on the failing reasons? I can't find the job in D365 in the job history (explains upload fail bad request) but I have no clue on how to debug this.

**Comment by TomekMelissa** [comment]
You need to look for clues in D365. In Prod it is difficult as you do not have direct access to eventlog of the server. Are you able to reproduce it on any sandbox?

**Comment by DarkSmile92** [comment]
We have a UAT System also running another RIS instance, I'll check if we can reproduce it there or if we can deploy a sandbox from prod. I'll update here asap

**Comment by v-crispadvice** [comment]
We faced the same issue and following errors were found in D365 event log:

`
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Microsoft-Dynamics-AX-ODataService" Guid="{DB19142A-6CD4-4C87-BAFB-9DFE55552F9D}" /> 
  <EventID>40</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>27</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x4000000100000004</Keywords> 
  <TimeCreated SystemTime="2020-01-27T09:17:38.609426700Z" /> 
  <EventRecordID>100424</EventRecordID> 
  <Correlation ActivityID="{80EB8F8A-D485-0007-35A0-EB8085D4D501}" /> 
  <Execution ProcessID="6444" ThreadID="2120" /> 
  <Channel>Microsoft-Dynamics-AX-ODataService/Operational</Channel> 
  <Computer>DEV-108P32-1</Computer> 
  <Security UserID="S-1-5-20" /> 
  </System>
<EventData>
  <Data Name="ComponentName">ODataService</Data> 
  <Data Name="exceptionMessage">System.InvalidOperationException: Exception occurred while executing action ImportFromPackage on Entity DataManagementDefinitionGroup: The data project 'Master Product In' exists and overwrite has not been specified. at Microsoft.Dynamics.Platform.Integration.Services.OData.Action.ActionInvokable.Invoke() at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateProcessor.ActionInvocation(ChangeOperationContext context, ActionInvokable action) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.<>c__DisplayClass14_0.<ScheduleInvokable>b__0(ChangeOperationContext context) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActionsInCompanyContext(IEnumerable 1 actionList, ChangeOperationContext operationContext) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActions(ChangeOperationContext context) at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.SaveChanges() at Microsoft.Dynamics.Platform.Integration.Services.OData.AxODataDelegatingHandler.<SaveChangesAsync>d__3.MoveNext()</Data> 
  <Data Name="infoMessage">An exception occured while calling SaveChanges on the UpdateManager.</Data> 
  </EventData>
  </Event>
`
We solved the problem by enabling "Overwrite data project definition" checkbox.

**Comment by DarkSmile92** [comment]
Thanks for the tip @v-crispadvice . We're currently working on setting up a sandbox environment to get access to the D365 eventlogs. 
We are facing this issue on a ExportJob, the option "Overwrite data project definition" is only available on ImportJobs.
![Bildschirmfoto_2020-01-27_10-58-17](https://user-images.githubusercontent.com/10928916/73165744-ac970e00-40f4-11ea-966e-427807b02a33.png)

**Comment by DarkSmile92** [comment]
Quick update:
Changing the settings from `Simple trigger` to `Cron trigger` with the same interval solved the second error with ExportJobs.

For the ImportJob problem, we set up a sandbox environment to replicate the error there, I'll update asap what the EventLog shows there.

**Comment by DarkSmile92** [comment]
We recognized that we encounter the errors with the ImportJobs when more than one job is running at the exact same time for different companies:
![image](https://user-images.githubusercontent.com/10928916/73438432-502f2b00-434e-11ea-9fce-bfe690c204d7.png)

One of them will always hang in status "Not run" and therefore produce the error.

**Comment by TomekMelissa** [comment]
You are hitting concurrency issues in D365. Please have a look at this thread on [Yammer](https://www.yammer.com/dynamicsaxfeedbackprograms/#/Threads/show?threadId=1148219025). Consider configuring your import jobs in such way that will avoid concurrency of the jobs

**Comment by DarkSmile92** [comment]
Thanks for the Yammer link. After changing the cron string on every import job to have 2 seconds delay to the one before, it seems to be working without any errors (Y)

**Comment by Samarjeet83** [comment]
I have download job scheduled in RIS for every one hour and that gets paused automatically in every 5-6 days and I have to resume  the job manually to run that again. I have some upload jobs also scheduled in RIS but that are working fine only upload jobs are getting paused. I have checked the error in event viewer which shows error -
Error-
The description for Event ID 0 from source Recurring Integrations Scheduler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Quartz.Core.JobRunShell - Job Download jobs.ProdPOLineDownload threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Download job: Download jobs.ProdPOLineDownload failed ---> Quartz.JobExecutionException: Job: Download jobs.ProdPOLineDownload. Failure response:  Status: BadGateway - BadGateway, Reason: Bad Gateway
   at RecurringIntegrationsScheduler.Job.Download.<Process>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Download.<Execute>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Download.<Execute>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Job: Download jobs.ProdPOLineDownload. Failure response:  Status: BadGateway - BadGateway, Reason: Bad Gateway
   at RecurringIntegrationsScheduler.Job.Download.<Process>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Download.<Execute>d__11.MoveNext()]

![RIS error in Event viewer](https://user-images.githubusercontent.com/87299807/125251377-db1e9e00-e314-11eb-821a-54dd1f5fd144.png)
