### ISSUE TITLE
Import job fails to generate mappings according to manifest

### ISSUE THREAD

**Issue by phillipsra16** [Microsoft/Recurring-Integrations-Scheduler#55]
When creating an import job and using a package file template with the headers and manifest, when the import job runs, it reads the manifest and creates the data project and adds the entity.  However, the mappings are generated incorrectly.  The "Ignore blank values" checkbox is honored, but fields removed from the mapping are not.  Default values are also not honored if the field does not exist in the file being imported.

This limits usability as not all integration partners are capable of producing a file with all the fields that need to be defaulted and/or send more fields than are needed.

This is for version 2.3 of RIS running on D365 8.0 PU 15

**Comment by TomekMelissa** [comment]
This is not related to RIS. Please file a support ticket for D365 if you feel it limits your implementation and should be fixed.
