### ISSUE TITLE
Upload Job - status: Redirect, reason found

### ISSUE THREAD

**Issue by Hasdy** [microsoft/Recurring-Integrations-Scheduler#56]
On premise-Platform Update 15

We have the following configured:
![2018-08-17_11-27-02](https://user-images.githubusercontent.com/8918752/44286134-3c107000-a225-11e8-988a-6293f9893749.jpg)

And getting the following exceptions in the event log:

`<Data>RecurringIntegrationsScheduler.Job.Upload - Job: Download jobs.Upload Job location. Enqueuing failed for file: C:\temp\RSIData\Input\{FD2A085F-68F2-4C5E-BA53-AA31B89159F5}.zip. Failure response: Status: Redirect, Reason: Found</Data>  `

And it does appear as though the job picks up the data package but throws it into the "Upload errors" directory with a status file.  Although the status file doesn't really contain a good error message....other than 
` "IsSuccessStatusCode": false`

Any help would be appreciated

**Comment by Hasdy** [comment]
Just to add.... it appears as though the issue is more on the instance configuration:
![2018-08-20_12-33-23](https://user-images.githubusercontent.com/8918752/44359568-7ff9b400-a475-11e8-94b5-4d6fc613cd1f.jpg)

I'm just not sure why that'd be the case.   Again....any help would be appreciated.

**Comment by AndreasHassing** [comment]
Try to use Package API. It seems like you're using enqueue/dequeue API which is not supported on-premise.

**Comment by Hasdy** [comment]
Fair enough.  To simplify our testing....we decided to attempt an "Export Job".  We have a test data project and a simply data entity to export.  
The following is our configuration.
![2018-08-21_10-05-59](https://user-images.githubusercontent.com/8918752/44414097-2f905e00-a52a-11e8-8ebe-85a38e2e4d1c.jpg)

Yet... the job will not break out of the "Blocked" Trigger status.  We've seen this before on our other attempts and have toggled between pause and resume....which usually worked.  But not in this case.

Any ideas on how to proceed.
Any help is appreciated.

**Comment by Hasdy** [comment]
Saw issue #21.  We removed all jobs and restarted the service; so in theory, there are no quartz jobs that are running....right?

Then we created a fresh new job and yet the job is created in a blocked state.  We can pause it...but it will never resume to a Normal state.

Ideas?

**Comment by TomekMelissa** [comment]
Please use v.2.4.0 This one fixes the interval issue

**Comment by SwathySubramani** [comment]
RIS - On premise- D10 Platform Update 24 
![RIS_Warning](https://user-images.githubusercontent.com/50476895/58224647-2bed6a00-7d3c-11e9-9f46-3e344fbcded4.png)

Facing authentication warning , Warning! HTTP response status for D365FO instance is Redirect Found.

@Hasdy : Kindly suggest if have fixed the issue.

**Comment by Hasdy** [comment]
@SwathySubramani I get that warning on the validate......but the jobs still work.  So we just ignore it.

**Comment by SwathySubramani** [comment]
@Hasdy , In my case both the upload / download jobs are not working.

I have created a Recurring job in  D365 F&O - On-Premise environment and linked the activity Id in the Job in Recurring Integration scheduler.

As per my knowledge, For On-Premises, the enqueue and dequeue API doesnt work.  Data Package management API  replaces that.  and the Data Management Package API would work as part of framework or is there any config or setup to link the Data management API to RIS. Not sure what I am missing.  Kindly suggest.

PFA., screenshots of the setup done in D365 F&O On- Prem end and in RIS.

D365 F&O( D10 Platform Update 24) setup :
![D365_ClientIdSetup](https://user-images.githubusercontent.com/50476895/58420786-da324000-80ab-11e9-85d8-827f119bc563.png)
![D365_JobRecurrance](https://user-images.githubusercontent.com/50476895/58420818-f209c400-80ab-11e9-9d6e-fc00f93fc60d.png)

Setup done in RIS (2.7.1) Version  :
![RIS_BatchJob](https://user-images.githubusercontent.com/50476895/58421144-e2d74600-80ac-11e9-8f7d-4d3e26ff8fe8.png)
![RIS_DownloadJob](https://user-images.githubusercontent.com/50476895/58421347-5e38f780-80ad-11e9-9bd9-5227805648b4.png)
![RIS_UploadJob](https://user-images.githubusercontent.com/50476895/58421520-c25bbb80-80ad-11e9-9633-f543d4a12e15.png)

**Comment by AndreasHassing** [comment]
If I recall correctly, upload and download jobs are using the enqueue/dequeue API @SwathySubramani.

Try creating "Export job" and "Import job" instead, which I believe uses the Package API.

**Comment by SwathySubramani** [comment]
@AndreasHassing  Thanks for your inputs. I was able to export the data package with Export Job.

When I am importing the data package  with RIS ( 2.7.1 version) , the import job is executed and the files are moved to error folder always.

Find below the setup done for Import Job in RIS.
![RIS_ImportJob](https://user-images.githubusercontent.com/50476895/58625563-587f2400-82f0-11e9-8d8f-f7c59c05aa06.png)

As per the error log, the authentication is sucessful and post the request URI for ImportFromPackage , the status code is set to false.

**Error File Log :**
"IsSuccessStatusCode": false

The request uri is, https://[baseURL]/namespaces/AXSF/data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.ImportFromPackage
![RIS_ImportErrorLog](https://user-images.githubusercontent.com/50476895/58625618-764c8900-82f0-11e9-9fc9-5df1e94970d4.png)

**Event log Error:**
![RIS_EventLog](https://user-images.githubusercontent.com/50476895/58625649-84020e80-82f0-11e9-9dda-6f199292425a.png)

@Hasdy / @AndreasHassing , Kindly suggest.

**Comment by TomekMelissa** [comment]
what is the result if you try to upload your package manually?
Try witch checked "Overwrite data project definition"

**Comment by SwathySubramani** [comment]
@TomekMelissa , I tried 'overwrite data project definition' also. facing the same issue.   And if I try to upload manually in D365 F&O and import , package is imported successfully.

**Comment by TomekMelissa** [comment]
Can you access Event log of your target instance? If yes then try to import your package again and check the logs on D365 side. The most convenient way is to create Custom view with Warnings and Errors for all logs under Applications and Services logs\Microsoft\Dynamics

**Comment by SwathySubramani** [comment]
@TomekMelissa , There is  error or warnings recorded in Event log on D365 Side.

**Comment by TomekMelissa** [comment]
This seems very unlikely. Could you verify if you are looking in D365 logs? Internal Server Error shown above clearly indicates that there should be an error in logs on D365 side.

**Comment by kiran211** [comment]
> @TomekMelissa , There is error or warnings recorded in Event log on D365 Side. I have verified that as well.
Did any one find solution for this. I'm facing same issue now.

**Comment by kiran211** [comment]
> @TomekMelissa , There is error or warnings recorded in Event log on D365 Side. I have verified that as well.

SwathySubramani Did you find solution for this? we are facing similar issue now. Please let me know how is it resolved.

**Comment by AndreasHassing** [comment]
@kiran211 see @TomekMelissa's response; there must be some logs of failure in D365, can you post those to this issue?

> This seems very unlikely. Could you verify if you are looking in D365 logs? Internal Server Error shown above clearly indicates that there should be an error in logs on D365 side.

**Comment by SwathySubramani** [comment]
@Kiran211, The issue in my case was the search pattern (File extension was not mentioned correctly).  Please verify if are passing that value correctly.

**Comment by kiran211** [comment]
Hi Swathy, I gave file extension as .xlsx and my data project also is created with .xlsx. Also I tried by providing *.* also. Please let me know if I need to use always .zip file

**Comment by kiran211** [comment]
> @kiran211, The issue in my case was the search pattern (File extension was not mentioned correctly). Please verify if are passing that value correctly. 

Hi swathy,
I'm using file extension as .xlsx will it be an issue. Also i tried by providing *.* in file extension. 
Please let me know how you were able to find this as issue

**Comment by MasRIS** [comment]
Hi, can anyone help with the question if upload and download RIS jobs are working with D365 FO on-premise now?

**Comment by AndreasHassing** [comment]
> Hi, can anyone help with the question if upload and download RIS jobs are working with D365 FO on-premise now?

@MasRIS Please see this: https://github.com/microsoft/Recurring-Integrations-Scheduler/issues/23#issuecomment-378918094

Only Package API is supported for D365 FO on-premises- there are no plans to support D365-scheduled import and export jobs.
