### ISSUE TITLE
RIS is not adding Input files into the package template zip

### ISSUE THREAD

**Issue by NSR23** [Microsoft/Recurring-Integrations-Scheduler#59]
### Expected behavior and actual behavior.
Whereas the import job works fine when I'm not setting any package template and provide a zip in the Input folder (the D365 Import Project is correctly triggered and executed), nothing happens when I provide a package template and then put my data files (csv files) in the Input folder. 

I'm expecting RIS to add my csv files into the zip file and trigger the execution of the Import in D365.

I have tried to use a package template with csv files inside and then also without (with only manifest and PackageHeader files)

### Steps to reproduce the problem.
add an Import Job in RIS, specify a package template, copy the data files to be added in the zip in the Input folder

### Specifications like the version of RIS and platform and application version of D365FO.
RIS 2.4.0.0
D365 7.2 PU15

**Comment by TomekMelissa** [comment]
Please specify more details, screenshots, enable DEBUG level in service config file and provide content of event log. What you are saying right now is that very basic feature of RIS does not work, but I cannot repro this. With proper configuration imports should work as expected.

**Comment by NSR23** [comment]
Thanks a lot for taking a look at my issue. Very likely, this issue is due to my misunderstanding. Let me share more details.

here is my folders structure
![image](https://user-images.githubusercontent.com/43003286/45219279-a65b8400-b2aa-11e8-849b-4c9ceec0e90f.png)

this config works prefectly well when I copy the file Allegro_workers_pkg_few.zip in the Input folder.
![image](https://user-images.githubusercontent.com/43003286/45219426-2b469d80-b2ab-11e8-8c0d-c26ed1fbda62.png)

With the config below, my understanding is that any file found in the Input folder would be added into the template zip file (Allegro_workers_pkg_template.zip) and then the D365 import project is triggered; I suppose that I would find the final zip file in the UploadSuccess folder.
![image](https://user-images.githubusercontent.com/43003286/45220674-300d5080-b2af-11e8-992e-a17445131883.png)

I have copied the file Allegro.csv in the Input folder. 
After my RIS job was executed, the csv is still there in the Input folder and nothing is triggered in D365.
Changing the Search pattern to .csv in the job is worth and not compatible with my D365 project!

thanks for your support, appreciated!

**Comment by TomekMelissa** [comment]
change Search pattern to match your input files in your second scenario. It should be *.csv. In your current setup RIS does not find anything in your input folder because it is looking for zip files.

What do you mean by this: _Changing the Search pattern to .csv in the job is worth and not compatible with my D365 project!_

**Comment by NSR23** [comment]
My data package contains 3 csv files, manifest file is set accordingly: Allegro.csv, Jobs.csv, Departments.csv

Normal execution triggered by RIS with a zip file in Input
(nb of records show that Allegro.csv file was correctly used for the 4 last entities, Jobs.csv ok with KUDJobEntity, the Failure on KUDDepartmentEntity is “normal” in this test case):
[cid:image002.jpg@01D446D5.1A076E60]





If I change the search pattern to *csv, RIS triggers three D365 imports. They are not properly executed and order is not ok: I need to have Jobs 1st, then Depts, then all other entities.
2 and 3 will never be executed by D365 (my tests from yesterday are still pending…)



  1.  File Allegro.csv (4 records) correctly used by 4 entities:
[cid:image005.jpg@01D446D5.1A076E60]


  1.  Entity KUDDepartmentEntity is mapped with the file Departments.csv in the manifest

[cid:image007.jpg@01D446D5.1A076E60]



  1.  3rd execution is like the 2nd and shows only KUDDepartmentEntity (I would be less surprise to see KUDJobEntity, mapped with Jobs.csv)

[cid:image012.jpg@01D446D5.1A076E60]

**Comment by TomekMelissa** [comment]
Please edit your response. Attachments were cut off from your email reply.

**Comment by TomekMelissa** [comment]
RIS will create a package (based on a template) for one entity inside only (one entity, one input file). If you have multiple entities that you want to send in one package then you need to create package outside of RIS.

**Comment by NSR23** [comment]
Thanks a lot for this feedback. It’s clear and I’ll keep the external script that we have already put in place for zipping.
Will be maybe improved in some future version.
Anyway, v2.4.0.0 is already much better than old 1.0.0.0 :)

**Comment by NSR23** [comment]
Thanks a lot for this feedback. It’s clear and I’ll keep the external script that we have already put in place for zipping.
Will be maybe improved in some future version.
Anyway, v2.4.0.0 is already much better than old 1.0.0.0 :)
