### ISSUE TITLE
Blocking Status

### ISSUE THREAD

**Issue by fhburney** [Microsoft/Recurring-Integrations-Scheduler#60]
When using the import job I am seeing Blocking status in the trigger status after it finds file.

I drop the file
It sees the file and status is updated to blocking
after 5 minutes the file is uploaded and status back to normal.

Any ideas on this, I am on platform 8 update 15

**Comment by TomekMelissa** [comment]
This is an issue i believe was fixed in 2.4.0. What version are you using?

**Comment by fhburney** [comment]
Yes this is the latest 2.4.0 version I am using. I do not remember if uninstalled the old version before reinstalling the new version. 

Also If I am trying to debug through visiual studio, it never hits the breakpoint if I put any, is there a specific way of debugging code in visual studio?

**Comment by TomekMelissa** [comment]
For debugging you should use standalone scheduler instead of service.

**Comment by fhburney** [comment]
uninstalled completely and reinstalled, same issue of going into blocking status.
Sounds good, I will debug this, can you point the piece of code where these status can usually assigned from upload job? so its easier for me where to put brekapoints on this

Thanks

**Comment by fhburney** [comment]
The below code, which executes the D365 importpackage is taking this long. the batch job to import in D365 shows up after 5 minutes. Not sure what is making D365 to wait 5 minutes to process this

![image](https://user-images.githubusercontent.com/28990985/45372447-e4ee8880-b5a1-11e8-92ee-b2e54bb4c168.png)

**Comment by fhburney** [comment]
Further more on this, I read all the logs, the file is uploaded instantly, however the following step in D365 is taking 3-4 minutes and causing this delay
Here are the time stamps, on the aos with DIXF on it you can read the log
![image](https://user-images.githubusercontent.com/28990985/45375462-df953c00-b5a9-11e8-83b1-6761923e80f6.png)

here is the D365 code, which gets executed and takes lot of time

![image](https://user-images.githubusercontent.com/28990985/45375544-2420d780-b5aa-11e8-9ebf-55ab9b6932c3.png)

**Comment by TomekMelissa** [comment]
Well, as you clearly see it has nothing to do with RIS. If you feel that import takes too long then I suggest to open support ticket with MS Support.

**Comment by fhburney** [comment]
@TomekMelissa 
I found the solution.
The method importFromPackage is depreicated and right method to use is importFromPackageV2

I update my odata point to importFromPackageV2

Further, there is a parameter which default to true, and if true it refreshes data entities on each time you call it, that was taking 5 minutes
So solution was i modified the code and added those parameter

Here is the D365 method, we want internal call to be true so it does not sync up data entities ( what a weird implementation seriously, making a syn each time)

![image](https://user-images.githubusercontent.com/28990985/45384362-af0dcc00-b5c2-11e8-85d1-5c0728c2526e.png)

now on the RIS side I added all those parameter and updated the oDATA, volla no more issues

![image](https://user-images.githubusercontent.com/28990985/45384457-f72cee80-b5c2-11e8-84d6-e3794027a21b.png)

You might want to update RIS with this, if this helps everyone on latest version

**Comment by fhburney** [comment]
I thought I found a fix but I did not, in short what is happening is the call causes data entity sync, which takes up that 5 minute.
On internal calls, that flag is turned off, so from UI it is fast, i could not find a way such that we call that latest method and set that flag so we do not sync everytime
Maybe I will create a ticket with MS, this is absurd if they have not made that flag available to be turned off through the API call

**Comment by TomekMelissa** [comment]
Thank you for this investigation. I was not aware of those recent changes. I will follow up internally.

**Comment by fhburney** [comment]
@TomekMelissa 
This might be helpful for you in next version. in the API there is anther method called which does not has this issue

![image](https://user-images.githubusercontent.com/28990985/45449875-4d656480-b68b-11e8-8e1a-94e11cf43040.png)

I updated the source code to point to this end point
![image](https://user-images.githubusercontent.com/28990985/45449922-70901400-b68b-11e8-8fad-4f6322a771de.png)

updated the source code to add those parameters

![image](https://user-images.githubusercontent.com/28990985/45449973-987f7780-b68b-11e8-93d1-9602c892958d.png)

runs fasts in async mode with no blocking

**Comment by easywithD365** [comment]
@TomekMelissa, which "next version" you are referring to ?
