### ISSUE TITLE
Option to pause jobs permanently

### ISSUE THREAD

**Issue by VadimGoncharenko** [Microsoft/Recurring-Integrations-Scheduler#61]
The option to put the job on hold permanently is needed badly at times, when you discover a problem and want to stop processing while investigating it. Pausing triggers works, but only till RIS service restarts, then the trigger is back to a Normal state. UI option (or something more robust than rescheduling to DEC 31st 2099) would help a LOT

**Comment by TomekMelissa** [comment]
It won't be implemented. Please delete such job from schedule.

**Comment by TomekMelissa** [comment]
see this #45

**Comment by VadimGoncharenko** [comment]
It is a shame, deleting dozens of jobs in production and recreating them later only because of being unable to pause them securely is an unnecessary effort and a risk I am trying to avoid. Anyway, there are (ugly) workarounds I can go for, thanks for a fast response
