### ISSUE TITLE
Validate error when authentication via user

### ISSUE THREAD

**Issue by P-Chon** [Microsoft/Recurring-Integrations-Scheduler#64]
### Specifications like the version of RIS and platform and application version of D365FO.

RIS version 2.4.0.0

Please help me. 
below is error description.

One or more errors occurred.
AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.
Trace ID: 19072c09-bf6c-4c36-b128-b12280421700
Correlation ID: 027eb21c-9133-401e-b929-36272fb4a437
Timestamp: 2018-10-11 03:10:53Z
Response status code does not indicate success: 401 (Unauthorized).
{"error":"invalid_client","error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: 19072c09-bf6c-4c36-b128-b12280421700\r\nCorrelation ID: 027eb21c-9133-401e-b929-36272fb4a437\r\nTimestamp: 2018-10-11 03:10:53Z","error_codes":[70002],"timestamp":"2018-10-11 03:10:53Z","trace_id":"19072c09-bf6c-4c36-b128-b12280421700","correlation_id":"027eb21c-9133-401e-b929-36272fb4a437"}: Unknown error

**Comment by AndreasHassing** [comment]
Looks like you are trying to validate with a user that does not have a secret specified in RIS. Can you please verify that the user does in fact have a key set?

**Comment by P-Chon** [comment]
Thank you for feedback AndreasHassing.

If I choose authentication type is User, cannot input client secret.

What should I do?

**Comment by TomekMelissa** [comment]
Please confirm that you are using so called Native App registered in your AAD and confirm this is really what you want to do. You should, most likely, use Web app and app secret.

Follow the steps here https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page

Note, that the header there says **Register a native application with AAD**, but in fact steps are describing web app registration.
