### ISSUE TITLE
Import Processing with Vendor Invoices Header, Lines, Document Attachment fails to Process

### ISSUE THREAD

**Issue by Christilley** [Microsoft/Recurring-Integrations-Scheduler#68]
### Expected behavior and actual behavior.

We are seeing an issue trying to use an import job to bring in the following entities.
Vendor Invoice Header
Vendor Invoice Lines
Vendor Invoice Document Attachment.

We created the template for the Data Package by exporting from a D365 Finance and Operations Environment.  This was populated with correct data for the target environment.

We tested this created package via the Data Management Workspace GUI in the client, and the import works correctly.  The Invoice is created along with the attachment.

If we try and do this via the RIS tool we get the below error.  The invoice itself (header and lines) is processed OK but the attachment fails.

The Import Job to FinOps succeeds with no error in the RIS tool, but the Source to Target processing then fails.

Can you tell if this a problem with the tool, how we've created the package, D365FO API or something else?

Vendor Invoice Document Attachment Failed:
Results. update not allowed for field 'Line reference(HeaderReference)'
Results. Validations failed

### Steps to reproduce the problem.
Create Data package with Vendor Invoice Header, Vendor Invoice Lines, Vendor Invoice Document Attachment.

Attempt to import via RIS
### Specifications like the version of RIS and platform and application version of D365FO.
RIS Version: 2.40
D365FO: PU20, Application: 8.0

**Comment by TomekMelissa** [comment]
Please contact MS Support. RIS is only transport solution and uses standard API. What happens in D365 after API call cannot be controlled by RIS.

**Comment by Christilley** [comment]
Thank you for response, looks like other users are seeing this issue too in Yammer groups
