### ISSUE TITLE
Upload of XML with import job type

### ISSUE THREAD

**Issue by diegomancassola** [Microsoft/Recurring-Integrations-Scheduler#7]
Using the "old" unsupported UPLOAD JOB type it's possible to choose if upload a ZIP or a XML file.

Using IMPORT JOB type it possible to upload only package ZIP files.

It will be nice if it supports the upload of specific entity XML file too, consider an real integration scenario, it's better to request to another application to give us an XML instead a complex package ZIP.

**Comment by TomekMelissa** [comment]
Upload method is supported. RIS can create simple packages for you (using "template"), so your internal app can still deliver "raw" files, not packages.

**Comment by diegomancassola** [comment]
Thanks a lot, but, i try to use the template method, but every time still get BAD REQUEST response from Dynamics. Can you give me more information about using of template?

**Comment by buttsj** [comment]
Having the same BadRequest issue with Import (recommended)

**Comment by TomekMelissa** [comment]
Make sure that you are using valid configuration of instance and AAD app registration. Try simple export job to validate.
Try to use Fiddler to see if there is more info in exception thrown by D365FO. I will add better error handling of new apis in near future.

**Comment by buttsj** [comment]
Yeah I've verified that my D365FO instance is valid by having no problems with Export (recommended).

I have a .zip "template" that contains an xlsx file with table headers, a Manifest file, and a PackageHeader file (this was all exported from a D365 Data Project set to Import).

Then I put an xlsx file with the new records in the Input and it goes straight to my UploadErrors folder with the BadRequest status.

Does anything seems incorrect based on that?

**Comment by TomekMelissa** [comment]
Remove xlsx file from template. It should only contain two files: manifest and header.

**Comment by diegomancassola** [comment]
I try to do that, but i can't understand the main point, on the input directory i have to put the XML or a ZIP contains the same files of package template plus the XML?

**Comment by buttsj** [comment]
That did the trick @TomekMelissa . Thank you!

**Comment by TomekMelissa** [comment]
@diegomancassola Input folder is where your other app stores input files (in your case xml files). Package template zip file you can store somewhere else. It can be folder above Input folder or anywhere. RIS is scanning Input folder for new files. When found it will zip every file, into template zip and it will send the result (data package - zipped input xml + manifest + package header) to D365FO. 

This is excerpt from wiki:
**Package template**: Path to package template file. When specified then job will zip source files from Input folder into package template “envelope”. Package template needs to be in sync with file format and content. When this file is empty then it is assumed that files in Input folder are already data packages

**Comment by diegomancassola** [comment]
@TomekMelissa Thanks a lot, i had understood that, but i got everytime a bad request. I need only a confirm if i had understood correctly. That's all. I'll try to setup the system again and try to have, using fiddler, some more information about bad request. Thanks a lot.

**Comment by diegomancassola** [comment]
@TomekMelissa Finnaly i can uplaod the XML single file instead package using a template. Thanks a lot.
