### ISSUE TITLE
integration scheduler with D365 on premise

### ISSUE THREAD

**Issue by koenpt** [Microsoft/Recurring-Integrations-Scheduler#74]
Hi all,
we're facing an issue to use recurring integration scheduler with D365fo on premise. We registered the application in adfs (because it's D365fo on-premise) and granted the application permissions in adfs and d365fo. but what isn't clear is what we need to fill out for "Auth endpoint" and "tenant" if we create the D365 instance in the parameters of integration scheduler.  Any help would be appreciated. kind regards

**Comment by percyzone** [comment]
AOS URL: https://[URL]/namespaces/AXSF
Auth endpoint: https://sts1.[DOMAIN]
Tenant: adfs

Example:
AOS URL: https://ax.d365ffo.onprem.percynxumalo/namespaces/AXSF
Auth endpoint: https://sts1.percynxumalo.com
Tenant: adfs

**Comment by koenpt** [comment]
I used the following to get it to work on my on-prem:

Variable

Description

AOS url

URL for the AOS
Cloud deployment:
https://{D365FO_ENVIRONMENT_BASE_URL}
On-prem deployment:
https://{D365FO_ENVIRONMENT_BASE_URL}/namespaces/AXSF

Auth endpoint

Cloud deployment:
https://login.microsoftonline.com

On-prem deployment:
https://{ADFS_ENVIRONMENT_BASE_URL}/adfs/oauth2

Tenant

Tenant Id for your instance. This is the tenant that was used to deploy the D365FO instance. It can be domain name or GUID

Cloud deployment:
{Tenant}

On-prem deployment:
adfs


Regards,

Koen
