### ISSUE TITLE
start RIS with startparameter

### ISSUE THREAD

**Issue by KateDL** [Microsoft/Recurring-Integrations-Scheduler#78]
Hello,

is there any possibility to start the RIS-Exe as standalone-scheduler immediately?

Thanks

Kathrin

**Comment by TomekMelissa** [comment]
Not at the moment. Why do you need such feature?

**Comment by KateDL** [comment]
i want to restart the RIS by batch or powershell as standalone scheduler.

**Comment by KateDL** [comment]
Because if an Export Job not running correctly the job goes to status 'blocked'. At the next time the export job should start, it is not working because of the status.

**Comment by KateDL** [comment]
Hello, 
here is some more Information to my problem with the status 'blocked'.

e.g. i habe an Export Job that is scheduled to 20:40 pm. this is a screenshot of the event log.
![image](https://user-images.githubusercontent.com/45535323/49690302-e3941400-fb2e-11e8-8278-be6f8edf1b00.png)

At the same time there is another log entry to the same export.
![image](https://user-images.githubusercontent.com/45535323/49690313-032b3c80-fb2f-11e8-9c93-1cb642cbd6c7.png)

the Export is going to blocked and is not working at the next time. But the export is running to the scheduled time, if the RIS is restarted.

Thanks for you help!

Kathrin

**Comment by TomekMelissa** [comment]
It is D365 issue with Async export. Contact MS support
