### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by jackyclever** [Microsoft/Recurring-Integrations-Scheduler#79]
### Specifications like the version of RIS and platform and application version of D365FO.

Entity name(tag name) should not be case sensitive. It was camel case in 8.0, in 8.1.1 this changes to upper case, and this doesnt work anymore.

**Comment by stefanlundquist** [comment]
There is a flighted feature in D365 that turns on camel case again

**Comment by TomekMelissa** [comment]
This is driven by D365 not RIS.
