### ISSUE TITLE
Error using upload job

### ISSUE THREAD

**Issue by tanujonactuate** [Microsoft/Recurring-Integrations-Scheduler#8]
### Expected behavior and actual behavior.
Expected customer group record to upload in D365FO but instead file moved into error folder
### Steps to reproduce the problem.
Tried any file to upload but same error is coming. I have attached the status file received in error folder.

[CustomerGroup-Customer groups_1.txt](https://github.com/Microsoft/Recurring-Integrations-Scheduler/files/1374900/CustomerGroup-Customer.groups_1.txt)

### Specifications like the version of RIS and platform and application version of D365FO.
RIS version 1.0.0
D365FO - 7.0.1265.23020

**Comment by TomekMelissa** [comment]
Make sure you provided valid Activity Id of data job. Double check if the client id you are using is authorized to use it.

**Comment by TomekMelissa** [comment]
Did you solve this issue?

**Comment by tanujonactuate** [comment]
Earlier we were trying to connect to d365 classic (May edition) with user authentication.  Later we connected to update 10 with service to service.  Then it worked fine.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TomekMelissa** [comment]
Thanks for update. Closing
