### ISSUE TITLE
Any incompatible changes since v1.0.1?

### ISSUE THREAD

**Issue by anqooqie** [Microsoft/Recurring-Integrations-Scheduler#80]
We are using Recurring Integrations Scheduler v1.0.1, and planning to update it to the latest version (v2.6.0 at this time).
I am not sure that this project follows the Semantic Versioning, but, if so, a major release should indicate that it has some kind of incompatible changes.

So I have a question.
Could you tell me whether v2.6.0 has any incompatible changes since v1.0.1?
Also, if the answer is YES, could you tell me how to update Recurring Integrations Scheduler correctly?

**Comment by TomekMelissa** [comment]
You need to uninstall old version completely and install and configure new one from scratch. There were changes in the way parameters are stored as well as in job definition (schedule.xml file). The safest way is to start from scratch.

**Comment by anqooqie** [comment]
@TomekMelissa We will try that. Thank you so much.
