### ISSUE TITLE
Currupt Schedule.xml on german windows

### ISSUE THREAD

**Issue by SteffenEngelhardt** [microsoft/Recurring-Integrations-Scheduler#83]
Hi.
First thanks fp the Tool. It´s really helpful.
I am using the RIS on a German Windows Server 2016.
When I try to save the Schedule.xml and restart the service the entries are still there.
After changing one Job to use "Cron expression" and overwrite the file, the content could not be loaded anymore from the schedule.xml file. Nothing is shown.

My suggestion why this happens is the timezone, as is shown like this in the xml.

 ```
<cron>
        <name>Trigger for job Export_Shared_Fibu_Mandanten.DPP</name>
        <group>DPP</group>
        <description>Trigger for job Export_Shared_Fibu_Mandanten.DPP</description>
        <job-name>Export_Shared_Fibu_Mandanten</job-name>
        <job-group>DPP</job-group>
        <misfire-instruction>SmartPolicy</misfire-instruction>
        <cron-expression>0 0/15 8-18 ? * MON-FRI *</cron-expression>
        <time-zone>Mitteleuropäische Zeit</time-zone>
      </cron>
```

INFO: Mitteleuropäische Zeit -> Central European Time

After removing the contents from time-zone, the RIS loads the file and executes it as expected.

Maybe you need to compare the "load" and "save" procedure what is different in it´s handling. Or maybe just leave it :-D

I did it on the latest version.
Kind regards

**Comment by AndreasHassing** [comment]
@SteffenEngelhardt It might be that all it takes is to swap out usage of [StandardName](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.standardname?view=netframework-4.5#System_TimeZoneInfo_StandardName) with [Id](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.id?view=netframework-4.5#System_TimeZoneInfo_Id) [here](https://github.com/microsoft/Recurring-Integrations-Scheduler/blob/11fc8a60583bc563811062e3bf4b94fcbac663ad/Scheduler/Scheduler.cs#L324).

**Comment by TomekMelissa** [comment]
Thank you @AndreasHassing I followed your suggestion.
