### ISSUE TITLE
IsAutoGenerated element in manifest not taken into account when project is created

### ISSUE THREAD

**Issue by VincentVerweij** [Microsoft/Recurring-Integrations-Scheduler#84]
### Expected behavior and actual behavior.
Actual:
I have a job in RIS, which creates an import project in D365FO. 
Its package template contains a manifest and in there I have a field which has IsAutoGenerated set to true.
The import package is created by RIS, but when I go to the created import project, look at the mapping details, the field that has auto generated on is nowhere to be found.

Expected is that the checkbox for Auto-Generated in D365FO is checked.

Note: I am not sure whether this is related to RIS or D365FO. If it is related to D365FO, please say so and close this issue.

When I turn off "Overwrite data project definition" in the job details and turn it on manually in D365FO, my files are processed correctly (so that is the work around).
### Steps to reproduce the problem.
1) Create an import project
2) Add entity "Project hour journal lines"
3) Open up the mapping details and I only added the following fields in the source:
- Category
- CostPrice
- CurrencyId
- Description
- DimensionDisplayValue
- Hours
- LineNumber
- LineProperty
- ProjectDate
- ProjectId
- ResourceCompanyId
- ResourceId
- VoucherDate

![image](https://user-images.githubusercontent.com/41574930/53963918-80465d80-40ee-11e9-8a53-57af0203de88.png)

3.1) Add new entry with Auto-Generated set to true and Staging field set to JOURNALID.

![image](https://user-images.githubusercontent.com/41574930/53964145-0d89b200-40ef-11e9-8690-ac88d4cc58cd.png)

4) Close the details, and click the Download button
5) Save the zip file
6) Open the zip file, remove the sample txt file
7) In the manifest, make the SampleFilePath empty, like so: &lt;SampleFilePath /&gt;
8) Create a new zip package for the Manifest and PackageHeader.
9) Use this file as the Package template

### Specifications like the version of RIS and platform and application version of D365FO.
RIS: 2.6.0.0
D365FO: 
Installed product version : Microsoft Dynamics 365 for Finance and Operations (8.1)
Installed platform version : Update23 (7.0.5126.35370)

**Comment by MZade** [comment]
@TomekMelissa The reason is that Dynamics 365 FO generates an error if you choose not to overwrite the project definition (in some cases). I think that behavior of D365FO is also not exactly logic.
