### ISSUE TITLE
File not fully processed in App10 Update 25

### ISSUE THREAD

**Issue by CraigLeea** [microsoft/Recurring-Integrations-Scheduler#86]
When running RIS under App10 update 25 the input file gets processed in the first step and going into the Upload Success Folder then for the monitoring job does not fully finish.
in D365 the file appears to have been processing, At least a journal has been created but the job history is showing a ?.  When looking at the executing summary the status is Unknown and also showing all records processed. 

 - Move file into Input folder, gets processed 1st time and stays stuck in the Upload Success folder, the log shows:
  "MessageStatus": "Enqueued",
  "DataJobState": "InProcess",

-Using RIS 2.7.1 with D365 App10U25

**Comment by TomekMelissa** [comment]
Looks like an issue on D365 side. Can you verify your files with direct upload?
