### ISSUE TITLE
Recurring Integration scheduler with On-Premises

### ISSUE THREAD

**Issue by SwathySubramani** [microsoft/Recurring-Integrations-Scheduler#88]
Trying to integrate Recurring Integration Scheduler (2.7.1)  with  D365 F&O On Premises D10 PU 24.
![RIS_Warning](https://user-images.githubusercontent.com/50476895/58227237-a53e8a00-7d47-11e9-86d6-1b24d8db8d31.png)

As per the attached image, it states the authentication is successful but with warning HTTP response status for D365FO instance is Redirect Found.

The files are not imported or exported, though the batch is scheduled in RIS , but executed from D365 end.

Kindly suggest.

**Comment by AndreasHassing** [comment]
@SwathySubramani please see https://github.com/microsoft/Recurring-Integrations-Scheduler/issues/56#issuecomment-496221474.
