### ISSUE TITLE
Upload of more than one XML at the same time

### ISSUE THREAD

**Issue by diegomancassola** [Microsoft/Recurring-Integrations-Scheduler#9]
### Expected behavior and actual behavior.
In our integration scenario we need to import packages with more than on XML inside, headers and rows for example, in a particolar sequence.

Our legacy application can't provide a finished data package .ZIP, too complex to give use the file, but they can send us only the specific 3 XML file. As writed on the Wiki import job using template can support only one entity at once, i think because the file system integration does not allow more than on file at once.

There's a plan to implement that option on the service? Mean the service can manage more than one XML file at the same time? I know is not so simple to do that, but using some tricks i think can be done, like naming 3 or more file with the same base name, or using a specific file to set the avaiability of the files.

### Specifications like the version of RIS and platform and application version of D365FO.
1.0.0 RIS
UPD10 D365FO

**Comment by TomekMelissa** [comment]
Import job and D365FO support importing packages with multiple entities inside. The condition is you need to provide such package. Template-based package creation feature of RIS import job will not work in this case. If you provide packages in input folder and leave template field empty then RIS should successfully upload those packages and D365FO will import those properly.
At this moment there are no plans to introduce such feature to RIS. It would be difficult to implement this feature to cover all possible scenarios, but it is probably fairly easy to implement "your specific need". This is where you can extend RIS and add your own "package creation" job type. I encourage you to fork RIS and do that.

**Comment by diegomancassola** [comment]
I have created a fork of the project, and now i can develop our needs. I have implemented a new job type, using SSIS packages. But, it will be nice if you implement a feature for uploading more XML using a template. IMHO can be very simple, instead search for new file, you can search for "folder", that folder can continain more than on file, entire folder contents can be zipped togheter on the same ZIP package

**Comment by MZade** [comment]
Hi @diegomancassola , Just be aware about the fact that a data project can only have one time a given entity assigned to. So, I'm not sure what will happen if we put different files related to the same entity in the same package? Did you alredy tried to create such a zip file and upload it manually to see what happens?
