### ISSUE TITLE
Import job only accepts package

### ISSUE THREAD

**Issue by EddieTANguyen** [microsoft/Recurring-Integrations-Scheduler#90]
### Specifications like the version of RIS and platform and application version of D365FO.

I setup RIS to use in On Premise D365 App 10.0.2 PU 26

After validated and tested export ok. I test an import job which import an .xlsx file to AX. However, the job failed to pick up the file and threw out error:

![image](https://user-images.githubusercontent.com/53469983/62116238-06548200-b2e4-11e9-9283-e603aceb0158.png)

I changed to package type and upload a zip file instead, then it worked normally. 

I am using newest version 2.7.1 of RIS.
![image](https://user-images.githubusercontent.com/53469983/62116580-9db9d500-b2e4-11e9-8678-19b86d821cf5.png)

**Comment by TomekMelissa** [comment]
Yes, this is by design of package API. read [this](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/data-management-api)
