### ISSUE TITLE
Data project changes to CSV from CSV-Unicode

### ISSUE THREAD

**Issue by rabol** [microsoft/Recurring-Integrations-Scheduler#92]
### Expected behavior and actual behavior.
I have a data project that is setup to have source format CSV-UNICODE
The .csv file is in uni code
But when the package is uploaded the data project changes to CSV and the execution fails with the error messages: Selected file is Unicode- '0' 'XXXX Packages' record(s) inserted in staging

The file is uni code and the data project is setup to accept uni code

If I uncheck the 'Overwrite project definition', then the upload fails

The expected behavior is that the file is uploaded and executed

### Steps to reproduce the problem.
ensure that you have a manifest.xml and a package.xml as a .zip in the template folder
Create a import data project in D365
Use a uni code .csv file as sample
validate that the source format is CSV-Unicode

Drop a uni code file in the 'input' folder
observe that the file is uploaded to D365
look at the execution log in D365

### Specifications like the version of RIS and platform and application version of D365FO.

D365 version:
Installed product version : Microsoft Dynamics 365 for Finance and Operations (10.0.4)
Installed platform version : Update28 (7.0.5314.35440)

RIS v2.7.1.0

**Comment by TomekMelissa** [comment]
Check manifest file in your package template. SourceFormat field at the end of the file. Manifest contains whole data project definition for your import.

**Comment by rabol** [comment]
Got it - Thanks
Maybe an update in the wiki :)
