### ISSUE TITLE
if there is no records in a file execution is of others are breaking

### ISSUE THREAD

**Issue by rabol** [microsoft/Recurring-Integrations-Scheduler#93]
### Expected behavior and actual behavior.

continuous integration with a different number of records in each file
file 1: 1000 records - first row is header
file 2: 10000 records - first row is header
file 3: 10000 records - first row is header
file 4: 0 records - first row is header

everything is working until file #4 with 0 records. Due to the fact that each file actually overwrite the project settings, then file #4 destroyed the field mapping and that breaks the execution of processing file #1, #2 and #3 if they are not totally process when file #4 is uploaded

### Steps to reproduce the problem.

Create a data project
Prepare 4 files, file #4 should only contain the header
put 3 files in the input folder
wait until D365 starts to process the files
put the 4th file in the input folder
After a short while the 3 previous files will fail to be processed as the field mapping gets destroyed

### Specifications like the version of RIS and platform and application version of D365FO.
Installed product version : Microsoft Dynamics 365 for Finance and Operations (10.0.4)
Installed platform version : Update28 (7.0.5314.35440)

**Comment by TomekMelissa** [comment]
This behavior of D365 not RIS. RIS is calling public APIs of D365 to upload package and initiate import. Everything else happens in D365.
I am not familiar with scenario where empty file is being uploaded, but if you use the same manifest in your package then I do not see the reason why data project's mapping are being "destroyed". On the other hand I would make sure that your source system or middleware does not produce empty files.
