### ISSUE TITLE
Exception : Value cannot be null. Parameter name: clientSecret

### ISSUE THREAD

**Issue by VincentVerweij** [microsoft/Recurring-Integrations-Scheduler#94]
### Expected behavior and actual behavior.
The jobs run without complaining about a clientSecret.

### Steps to reproduce the problem.
Haven't found a way to reproduce it. The only way is Edit the job (without editing any of the settings) and wait for it to happen again, 

### Specifications like the version of RIS and platform and application version of D365FO.
RIS version: 2.6.0
Number of jobs: 33
D365FO version: Microsoft Dynamics 365 for Finance and Operations (10)
Installed platform version : Update26 (7.0.5257.35417)

### More information
When a file is being dropped in the Input folder sometimes the file is processed, but sometimes it goes in error (see error below).

What I have found to temporarily fix it (even though it comes back), is to open up the job's settings and click the Edit button. This will will make the last run column empty, and the next time it is executed it works.

Because the setting "Pause job when exception occurs" is on, the job pauses as expected.

What I have checked so far:
- D365FO's Azure active directory applications contains a record with a user that has sys admin rights, and the client id is the same as the one available in Azure's Active Directory
- In the RIS parameters in section Azure AD applications I have re-entered the Client Id and Client secret
- The jobs are all using the same service as created in the RIS setting's Azure AD applications
- Open up job, change nothing, click the Edit button, it is retriggered and runs fine for a while

![Exception-details1](https://user-images.githubusercontent.com/41574930/66545555-42556000-eb3b-11e9-9950-c565308eda92.png)
[Exception-details-text.txt](https://github.com/microsoft/Recurring-Integrations-Scheduler/files/3710875/Exception-details-text.txt)

**Comment by TomekMelissa** [comment]
Client secret as any other job settings is being stored in Schedule.xml file in main folder of RIS. Unlike any other setting, secret is being encrypted using LocalMachine scope of ProtectedData API. It means that it can only be decrypted successfully on the machine where it was encrypted. If you open that file to edit it on another machine decryption will fail and empty string will be saved if do not provide secret again. It is possible to connect to scheduler instance from another machine, but you should never edit jobs in such connection due to this exact behavior. Such secret will not be readable by Scheduler service and value passed will be nulled.
Please edit your job on the machine where scheduler service is running, then open Schedule.xml and note AadClientSecret property value for the job. Next time it fails check this value again. If it is different then most likely someone edited the job from other machine.

**Comment by VincentVerweij** [comment]
We have the RIS running on a dev, test, acc and prod server. When the job is being altered, it is only possible to access it via RDP to the corresponding server. Currently I am the only one in the company here that is accessing it. And I always go to it via RDP, open up the RIS and perform the steps that I mentioned earlier.

If I understand it all well, the moment that I open up the the job and press the Edit job button, it will take the credentials that are available in the parameters, encrypt those on the server where it is running and fill in the AadClientSecret property. So that time it will run successfully. When it throws the clientSecret error, the AadClientSecret property has been altered in some way on another machine, right?

I will definitely keep an eye out on the schedule.xml AadClientSecret property.

**Comment by VincentVerweij** [comment]
I am wondering, when you press Edit job what clientSecret does it take into account? Does it fetch from the schedule.xml or does it take an internally new encrypted clientSecret? 

The reason why I am asking this, is that after clicking the Edit job button, it runs fine at first. But the next time I drop something in the input folder it throws the error. So my guess is that after pressing the Edit job button that it takes the right value which was entered in the RIS parameters. And next time it runs, it takes the value from the schedule.xml AadClientSecret property which is wrong (I checked it).

I pressed the Save schedule file button and saved it as a separate file and saw that the AadClientSecret property differs from the currently in-use schedule.xml, so it must have been altered on a different machine. I will investigate this, but I believe the above is something to look at?

I also noticed that when you Edit the job, the schedule.xml file is not altered, so I think my reasoning above is right, that it takes an internal value after editing the job, and next run it takes from the schedule.xml.

**Comment by TomekMelissa** [comment]
Scheduler service when it starts it will read Schedule.xml file and setup its job accordingly. This is the only moment when it reads that file - during startup.
Then, when you connect RIS app to the service it will display list of currently scheduled job in the scheduler service. When you edit job it will fetch the data from scheduler service, not from Schedule.xml. Similarly when you finish editing it will provide those new settings to the scheduler runtime directly. At the same moment Schedule.xml file will be marked as "update it required" and it will be saved when you close RIS app. So the next time Scheduler service is restarted it will configure all jobs with the proper configuration.
When you need to update settings such as client credentials or instance details, do this in RIS parameters first and then edit each job that uses those settings. It is not enough to update parameters only. You need to update jobs settings as well.

**Comment by VincentVerweij** [comment]
Thank you for the clear explanation of how it all works, learned some new things about RIS.

What do you think about the issue that I had, that it first runs ok and next time it goes in error with the clientSecret error. I checked and verified that there are no external sources altering the RIS schedule.xml file. Also in between the edit job and second run, there was no restart of the service. So could it be that there's a small bug in the runtime?

**Comment by TomekMelissa** [comment]
I doubt that. Double check your config. Make sure AAD client and secret is the same everywhere in your schedule.xml file. Restart RIS service and see if you encounter another issue like that.
BTW, update to 2.7.1

**Comment by VincentVerweij** [comment]
"secret is being encrypted using LocalMachine scope of ProtectedData API. It means that it can only be decrypted successfully on the machine where it was encrypted" was the solution. Recreating the jobs on the new machine resolved the issue.
