### ISSUE TITLE
Recurring Integrations Scheduler compatibility with 10.0.5/PU29.

### ISSUE THREAD

**Issue by YujiImaoka** [microsoft/Recurring-Integrations-Scheduler#97]
Our customer will upgrade from App7.1/PU24 to 10.0.5/PU29.
They are using Recurring Integrations Scheduler(ver1.0.1.0).
They would like to double check if ver1.0.1.0 supports App10.0.5/PU29.

**Comment by TomekMelissa** [comment]
Yes, it does. Of course please test your processes in upgraded sandbox first as you would do with any other component.
